Repository karmada-io/website, pull requests merged in 2022-05, with the labels that each got.

#40 update Supporters block
  src/css/custom.css
  src/data/supporters.js
  src/pages/index.js
  src/pages/styles.module.css
  static/img/supporters/T3-logo2.png
  static/img/supporters/VIPKID.png
  static/img/supporters/aiml.png
  static/img/supporters/chinamobile.png
  static/img/supporters/faw.png
  static/img/supporters/hualala.png
  static/img/supporters/huawei.png
  static/img/supporters/icbc.png
  static/img/supporters/qutoutiao.png
  static/img/supporters/spdb.png
  static/img/supporters/xiaohongshu.png
  static/img/supporters/youzan.png
Labels: approved, lgtm, size/L

#46 fix hero logotype
  src/pages/styles.module.css
Labels: approved, lgtm, size/S

#42 Setup code owners
  OWNERS
Labels: size/XS, kind/cleanup, approved, lgtm

#47 content centering
  src/css/custom.css
  src/pages/index.js
Labels: approved, lgtm, size/S

#45 Setup issue and PR template
  .github/ISSUE_TEMPLATE/enhancement.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: kind/cleanup, approved, lgtm, size/M

#49 How it works rescaled
  src/pages/index.js
Labels: size/XS, approved, lgtm

#53 refactoring supporters block
  src/components/supportersList.js
  src/data/supporters.js
  src/pages/index.js
Labels: approved, lgtm, size/M

#55 JointCloud Logo Commit
  src/data/supporters.js
  static/img/supporters/jointcloud.png
Labels: size/XS, approved, lgtm, kind/flake

#57 fix logo on mobile
  src/pages/styles.module.css
Labels: size/XS, approved, lgtm

#58 add post
  blog/2022-03-22-multi-cluster-management-with-an-ocean-of-nodes/img/image1.png
  blog/2022-03-22-multi-cluster-management-with-an-ocean-of-nodes/img/image2.png
  blog/2022-03-22-multi-cluster-management-with-an-ocean-of-nodes/img/image3.png
  blog/2022-03-22-multi-cluster-management-with-an-ocean-of-nodes/img/image4.png
  blog/2022-03-22-multi-cluster-management-with-an-ocean-of-nodes/img/image5.png
  blog/2022-03-22-multi-cluster-management-with-an-ocean-of-nodes/index.md
  blog/2022-04-07.md
Labels: approved, lgtm, size/L

#59 fix namespaces already exists error when registtering cluster with pu…
  docs/installation/installation.md
Labels: size/XS, kind/documentation, approved, lgtm

#61 add favicons for all devices
  docusaurus.config.js
  src/plugins/faviconCustomPlugin.js
  static/img/favicon.ico
Labels: kind/feature, approved, lgtm, size/M

#65 Add more spaces above Why Karmada
  src/css/custom.css
  src/pages/index.js
Labels: kind/feature, approved, lgtm, size/S

#66 [doc] sync override-policy.md from karmada
  docs/userguide/override-policy.md
  sidebars.js
  versioned_docs/version-v1.0.0/userguide/override-policy.md
  versioned_sidebars/version-v1.0.0-sidebars.json
Labels: kind/documentation, approved, lgtm, size/XL
