Repository karmada-io/website, pull requests merged in 2022-03, with the labels that each got.

#18 update copyright year
  config/_default/config.toml
Labels: size/XS, approved, lgtm, release-note-none

#19 Overrides the github link and adds docs button
  data/en/banner.yml
  layouts/partials/banner.html
Labels: approved, lgtm, size/S

#21 fix cloud native img
  themes/meghna-hugo/assets/css/style.css
Labels: size/XS, approved, lgtm

#16 fix hero area on tablet
  layouts/partials/banner.html
  themes/meghna-hugo/assets/css/style.css
Labels: approved, lgtm, size/M

#24 Add Hualala logo to supporters
  data/en/support.yml
  static/img/hualala.png
Labels: size/XS, approved, lgtm

#26 docs: add youzan
  data/en/support.yml
  static/img/youzan.png
Labels: size/XS, approved, lgtm

#27 Accessibility add link name
  layouts/partials/footer.html
Labels: size/XS, approved, lgtm

#23 add favicons
  layouts/partials/head.html
  static/favicons/android-chrome-192x192.png
  static/favicons/apple-touch-icon.png
  static/favicons/browserconfig.xml
  static/favicons/favicon-16x16.png
  static/favicons/favicon-32x32.png
  static/favicons/favicon.ico
  static/favicons/mstile-150x150.png
  static/favicons/safari-pinned-tab.svg
  static/favicons/site.webmanifest
Labels: approved, lgtm, size/M

#29 fix items on tablet & mobile
  layouts/partials/about.html
Labels: size/XS, approved, lgtm
