Repository karmada-io/website, pull requests merged in 2022-10, with the labels that each got.

#189 add dependabot.yml
  .github/dependabot.yml
Labels: kind/feature, size/XS, approved, lgtm

#193 add ecloud to karmada adopters
  docs/casestudies/adopters.md
Labels: kind/documentation, approved, lgtm, size/S

#182 Update troubleshooting.md
  docs/troubleshooting/troubleshooting.md
Labels: kind/documentation, approved, lgtm, size/S

#145 add contribute-docs article
  docs/contributor/contribute-docs.md
  docs/resources/contributor/click-next.png
  docs/resources/contributor/debug-docs.png
  i18n/zh/docusaurus-plugin-content-docs/current/contributor/contribute-docs.md
  i18n/zh/docusaurus-plugin-content-docs/current/resources/contributor/click-next.png
  i18n/zh/docusaurus-plugin-content-docs/current/resources/contributor/debug-docs.png
  sidebars.js
Labels: kind/documentation, approved, lgtm, size/L

#187 Distinguish karmadactl and kubectl-karmada
  docs/installation/install-karmadactl.md
  docs/installation/install-kubectl-karmada.md
  docs/installation/installation.md
  i18n/zh/docusaurus-plugin-content-docs/current/installation/install-karmadactl.md
  i18n/zh/docusaurus-plugin-content-docs/current/installation/install-kubectl-karmada.md
  i18n/zh/docusaurus-plugin-content-docs/current/installation/installation.md
  sidebars.js
Labels: kind/cleanup, approved, lgtm, size/M

#192 translation-docusaurus-plugin-content-docs/current/troubleshooting
  i18n/zh/docusaurus-plugin-content-docs/current/troubleshooting/troubleshooting.md
Labels: approved, lgtm, size/S

#196 Add release docs
  docs/releases.md
  i18n/zh/docusaurus-plugin-content-docs/current/releases.md
  sidebars.js
Labels: kind/documentation, approved, lgtm, size/L

#198 Add vivo to karmada adopters
  docs/casestudies/adopters.md
  i18n/zh/docusaurus-plugin-content-docs/current/casestudies/adopters.md
Labels: size/XS, approved, lgtm

#204 request for DaoCloud into Karmada Supporters
  src/data/supporters.js
  static/img/supporters/DaoCloud.png
Labels: size/XS, kind/documentation, approved, lgtm

#197 [zh] sync/administrator/monitoring/working-with-filebeat.md
  i18n/zh/docusaurus-plugin-content-docs/current/administrator/monitoring/working-with-filebeat.md
Labels: approved, lgtm, size/S

#200 [zh] sync/administrator/monitoring/working-with-prometheus.md
  i18n/zh/docusaurus-plugin-content-docs/current/administrator/monitoring/working-with-prometheus.md
Labels: approved, lgtm, size/S

#202 [zh] sync/administrator/backup/working-with-velero.md
  i18n/zh/docusaurus-plugin-content-docs/current/administrator/backup/working-with-velero.md
Labels: approved, lgtm, size/L

#209 Add Unicom Digital Tech to adopters
  docs/casestudies/adopters.md
Labels: kind/documentation, approved, lgtm, size/S

#212 [zh] sync faq.md
  i18n/zh/docusaurus-plugin-content-docs/current/faq/faq.md
Labels: kind/documentation, approved, lgtm, size/M

#205 Add install scripts
  docs/installation/install-cli-tools.md
  docs/installation/install-karmadactl.md
  docs/installation/install-kubectl-karmada.md
  docs/installation/installation.md
  docs/userguide/clustermanager/cluster-registration.md
  docs/userguide/scheduling/resource-propagating.md
  i18n/zh/docusaurus-plugin-content-docs/current/installation/install-binary.md
  i18n/zh/docusaurus-plugin-content-docs/current/installation/install-cli-tools.md
  i18n/zh/docusaurus-plugin-content-docs/current/installation/install-karmadactl.md
  i18n/zh/docusaurus-plugin-content-docs/current/installation/install-kubectl-karmada.md
  i18n/zh/docusaurus-plugin-content-docs/current/installation/installation.md
  i18n/zh/docusaurus-plugin-content-docs/current/userguide/clustermanager/cluster-registration.md
  i18n/zh/docusaurus-plugin-content-docs/current/userguide/scheduling/resource-propagating.md
  sidebars.js
Labels: size/XXL, kind/documentation, approved, lgtm

#211 [zh] sync /installation/install-cli-tools.md
  i18n/zh/docusaurus-plugin-content-docs/current/installation/install-cli-tools.md
Labels: kind/documentation, approved, lgtm, size/M

#216 [zh] sync contribute-docs.md
  i18n/zh/docusaurus-plugin-content-docs/current/contributor/contribute-docs.md
Labels: kind/documentation, approved, lgtm, size/L

#218 Fix link error
  docs/reference/karmadactl/karmadactl-commands/karmadactl.md
  docs/reference/karmadactl/karmadactl-commands/karmadactl_addons.md
  docs/reference/karmadactl/karmadactl-commands/karmadactl_addons_disable.md
  docs/reference/karmadactl/karmadactl-commands/karmadactl_addons_enable.md
  docs/reference/karmadactl/karmadactl-commands/karmadactl_addons_list.md
  docs/reference/karmadactl/karmadactl-commands/karmadactl_apply.md
  docs/reference/karmadactl/karmadactl-commands/karmadactl_cordon.md
  docs/reference/karmadactl/karmadactl-commands/karmadactl_deinit.md
  docs/reference/karmadactl/karmadactl-commands/karmadactl_describe.md
  docs/reference/karmadactl/karmadactl-commands/karmadactl_exec.md
  docs/reference/karmadactl/karmadactl-commands/karmadactl_get.md
  docs/reference/karmadactl/karmadactl-commands/karmadactl_index.md
  docs/reference/karmadactl/karmadactl-commands/karmadactl_init.md
  docs/reference/karmadactl/karmadactl-commands/karmadactl_join.md
  docs/reference/karmadactl/karmadactl-commands/karmadactl_logs.md
  docs/reference/karmadactl/karmadactl-commands/karmadactl_options.md
  docs/reference/karmadactl/karmadactl-commands/karmadactl_promote.md
  docs/reference/karmadactl/karmadactl-commands/karmadactl_register.md
  docs/reference/karmadactl/karmadactl-commands/karmadactl_taint.md
  docs/reference/karmadactl/karmadactl-commands/karmadactl_token.md
  docs/reference/karmadactl/karmadactl-commands/karmadactl_token_create.md
  docs/reference/karmadactl/karmadactl-commands/karmadactl_token_delete.md
  docs/reference/karmadactl/karmadactl-commands/karmadactl_token_list.md
  docs/reference/karmadactl/karmadactl-commands/karmadactl_uncordon.md
  docs/reference/karmadactl/karmadactl-commands/karmadactl_unjoin.md
  docs/reference/karmadactl/karmadactl-commands/karmadactl_version.md
Labels: approved, lgtm, size/M, kind/failing-test

#219 Modify the multi-cluster Service discovery and multi-cluster ingress documents
  docs/userguide/service/multi-cluster-ingress.md
  docs/userguide/service/multi-cluster-service.md
Labels: kind/cleanup, approved, lgtm, size/L

#208 Optimize anp document
  docs/userguide/clustermanager/working-with-anp.md
Labels: kind/cleanup, approved, lgtm, size/S

#161 Add blog `karmada-v1.3`
  blog/2022-09-06-karmada-v1.3/karmada-v1.3.md
Labels: kind/documentation, approved, lgtm, size/L

#221 Add note for mcs document: kubernetes version and pod/service CIDRs
  docs/userguide/service/multi-cluster-ingress.md
  docs/userguide/service/multi-cluster-service.md
  i18n/zh/docusaurus-plugin-content-docs/current/userguide/service/multi-cluster-ingress.md
  i18n/zh/docusaurus-plugin-content-docs/current/userguide/service/multi-cluster-service.md
Labels: kind/documentation, approved, lgtm, size/S

#203 Add huawei to adopters
  docs/casestudies/adopters.md
  i18n/zh/docusaurus-plugin-content-docs/current/casestudies/adopters.md
Labels: kind/documentation, approved, lgtm, size/M

#224 Fix typo in failover
  docs/userguide/failover/failover-analysis.md
  i18n/zh/docusaurus-plugin-content-docs/current/userguide/failover/failover-analysis.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.3.0/userguide/failover/failover.md
  versioned_docs/version-v1.3.0/userguide/failover/failover.md
Labels: size/XS, kind/cleanup, approved, lgtm

#222 Add document for ClusterID
  docs/userguide/clustermanager/cluster-registration.md
  i18n/zh/docusaurus-plugin-content-docs/current/userguide/clustermanager/cluster-registration.md
Labels: kind/documentation, approved, lgtm, size/S

#234 Add Zhejiang Lab to karmada adopters
  docs/casestudies/adopters.md
  i18n/zh/docusaurus-plugin-content-docs/current/casestudies/adopters.md
Labels: size/XS, approved, lgtm

#231 Fix typo in blog
  blog/2022-03-22-multi-cluster-management-with-an-ocean-of-nodes/index.md
Labels: size/XS, kind/cleanup, approved, lgtm

#213 Add docs for LabelsOverrider/AnnotationsOverrider
  docs/userguide/scheduling/override-policy.md
Labels: kind/documentation, approved, lgtm, size/M
