Repository karmada-io/website, pull requests merged in 2022-06, with the labels that each got.

#75 fix github icon on dark theme
  src/css/custom.css
Labels: kind/bug, size/XS, approved, lgtm

#78 Update async to version 2.6.4
  package-lock.json
  yarn.lock
Labels: kind/cleanup, approved, lgtm, size/S

#80 fix karmada icon on dark theme
  docusaurus.config.js
  static/img/artwork/karmada-icon-white.svg
Labels: kind/bug, size/XS, kind/design, approved, lgtm

#81 update supporters block on dark theme
  src/css/custom.css
Labels: kind/bug, kind/design, approved, lgtm, size/S

#83 refactor Why Karmada list
  src/components/featuresList.js
  src/data/features.js
  src/pages/index.js
Labels: kind/feature, kind/cleanup, approved, lgtm, size/L

#85 [doc] optimize text and layout of core-concept.md
  docs/getting-started/core-concept.md
Labels: kind/documentation, approved, lgtm, size/S

#86 [doc] text and layout optimization: docs/troubleshooting.md
  docs/troubleshooting.md
Labels: kind/documentation, approved, lgtm, size/M

#82 remove lock files
  README.md
  yarn.lock
Labels: kind/feature, size/XXL, approved, lgtm

#93 minor update site.webmanifest
  static/favicons/site.webmanifest
Labels: size/XS, approved, lgtm

#89 Update code.json
  i18n/zh/code.json
Labels: kind/documentation, approved, lgtm, size/M
