Repository karmada-io/website, pull requests merged in 2022-12, with the labels that each got.

#267 Add sidebar for upgrade 1.3-to-1.4
  docs/reference/karmadactl/karmadactl-usage-conventions.md
  i18n/zh/docusaurus-plugin-content-docs/current/reference/karmadactl/karmadactl-usage-conventions.md
  sidebars.js
Labels: kind/cleanup, approved, lgtm, size/M

#268 Add metrics for pool.
  docs/reference/instrumentation/metrics.md
Labels: size/XS, kind/documentation, approved, lgtm

#273 update document with resource-propagating.md
  docs/userguide/scheduling/resource-propagating.md
  i18n/zh/docusaurus-plugin-content-docs/current/userguide/scheduling/resource-propagating.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.4.0/userguide/scheduling/resource-propagating.md
  versioned_docs/version-v1.4.0/userguide/scheduling/resource-propagating.md
Labels: kind/cleanup, kind/documentation, approved, lgtm, size/S

#274 update karmadactl-usage-conventions.md
  docs/reference/karmadactl/karmadactl-usage-conventions.md
  i18n/zh/docusaurus-plugin-content-docs/current/reference/karmadactl/karmadactl-usage-conventions.md
Labels: kind/documentation, approved, lgtm, size/M

#276 Refacter resource propagation
  docs/key-features/features.md
  docs/userguide/scheduling/resource-propagating.md
  i18n/zh/docusaurus-plugin-content-docs/current/key-features/features.md
  i18n/zh/docusaurus-plugin-content-docs/current/userguide/scheduling/resource-propagating.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.4.0/key-features/features.md
  versioned_docs/version-v1.4.0/key-features/features.md
Labels: kind/documentation, approved, lgtm, size/L

#277 Fix releasing.md font
  docs/developers/releasing.md
  i18n/zh/docusaurus-plugin-content-docs/current/developers/releasing.md
Labels: approved, lgtm, size/S

#279 Add health check for RB/CRB
  docs/resources/userguide/cicd/argocd/argocd-2.6.0-status-overview.png
  docs/userguide/cicd/working-with-argocd.md
Labels: size/XS, kind/cleanup, approved, lgtm

#281 Supplement missing colon.
  docs/userguide/scheduling/override-policy.md
  i18n/zh/docusaurus-plugin-content-docs/current/userguide/scheduling/override-policy.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.4.0/userguide/scheduling/override-policy.md
  versioned_docs/version-v1.4.0/userguide/scheduling/override-policy.md
Labels: kind/cleanup, approved, lgtm, size/S
