Repository karmada-io/website, pull requests merged in 2022-07, with the labels that each got.

#97 fix routing duplicate on npm run start
  docs/README.md
  i18n/zh/docusaurus-plugin-content-docs/current/README.md
  versioned_docs/version-v1.0.0/README.md
Labels: kind/bug, approved, lgtm, size/S

#98 [docs] improve working-with-velero.md
  docs/casestudies/working-with-velero.md
Labels: kind/cleanup, approved, lgtm, size/S

#99 Improve working-with-prometheus.md
  docs/casestudies/working-with-prometheus.md
Labels: kind/documentation, approved, lgtm, size/S

#101 replace Button to components
  src/components/button.js
  src/pages/index.js
Labels: kind/cleanup, approved, lgtm, size/M

#103 improve introduction markdown content
  docs/getting-started/introduction.md
Labels: size/XS, approved, lgtm

#104 replace WhatIs to components
  src/components/whatIs.js
  src/pages/index.js
Labels: kind/cleanup, approved, lgtm, size/M

#111 fix: messed up document
  docs/userguide/resource-propagating.md
  versioned_docs/version-v1.0.0/userguide/resource-propagating.md
Labels: size/XS, kind/cleanup, approved, lgtm

#113 replace github btn to components
  src/components/gitHubButton.js
  src/pages/index.js
Labels: kind/cleanup, approved, lgtm, size/M

#119 [docs] updated /getting-started/architecture.md
  docs/getting-started/architecture.md
Labels: kind/documentation, approved, lgtm, size/S
