Repository karmada-io/website, pull requests merged in 2022-11, with the labels that each got.

#214 [zh] sync install-binary.md
  i18n/zh/docusaurus-plugin-content-docs/current/installation/install-binary.md
Labels: kind/documentation, approved, lgtm, size/L

#215 [zh] sync /casestudies/adopters.md
  i18n/zh/docusaurus-plugin-content-docs/current/casestudies/adopters.md
Labels: kind/documentation, approved, lgtm, size/M

#220 Add test report for Karmada1.3
  blog/2022-10-26-test-report/img/architecture.png
  blog/2022-10-26-test-report/img/mutating.png
  blog/2022-10-26-test-report/img/mutating_aggregated_apiserver.png
  blog/2022-10-26-test-report/img/pull_apiserver_qps.png
  blog/2022-10-26-test-report/img/pull_cpu.png
  blog/2022-10-26-test-report/img/pull_etcd_latency.png
  blog/2022-10-26-test-report/img/pull_memory.png
  blog/2022-10-26-test-report/img/pull_total.png
  blog/2022-10-26-test-report/img/push_apiserver_qps.png
  blog/2022-10-26-test-report/img/push_cpu.png
  blog/2022-10-26-test-report/img/push_etcd_latency.png
  blog/2022-10-26-test-report/img/push_memory.png
  blog/2022-10-26-test-report/img/push_total.png
  blog/2022-10-26-test-report/img/readonly_aggregated_apiserver.png
  blog/2022-10-26-test-report/img/readonly_cluster.png
  blog/2022-10-26-test-report/img/readonly_namespace.png
  blog/2022-10-26-test-report/img/readonly_resource.png
  blog/2022-10-26-test-report/img/test_architecture.png
  blog/2022-10-26-test-report/index.md
  i18n/zh/docusaurus-plugin-content-blog/2022-04-07.md
  i18n/zh/docusaurus-plugin-content-blog/2022-10-26-test-report/img/architecture.png
  i18n/zh/docusaurus-plugin-content-blog/2022-10-26-test-report/img/mutating.png
  i18n/zh/docusaurus-plugin-content-blog/2022-10-26-test-report/img/mutating_aggregated_apiserver.png
  i18n/zh/docusaurus-plugin-content-blog/2022-10-26-test-report/img/pull_apiserver_qps.png
  i18n/zh/docusaurus-plugin-content-blog/2022-10-26-test-report/img/pull_cpu.png
  i18n/zh/docusaurus-plugin-content-blog/2022-10-26-test-report/img/pull_etcd_latency.png
  i18n/zh/docusaurus-plugin-content-blog/2022-10-26-test-report/img/pull_memory.png
  i18n/zh/docusaurus-plugin-content-blog/2022-10-26-test-report/img/pull_total.png
  i18n/zh/docusaurus-plugin-content-blog/2022-10-26-test-report/img/push_apiserver_qps.png
  i18n/zh/docusaurus-plugin-content-blog/2022-10-26-test-report/img/push_cpu.png
  i18n/zh/docusaurus-plugin-content-blog/2022-10-26-test-report/img/push_etcd_latency.png
  i18n/zh/docusaurus-plugin-content-blog/2022-10-26-test-report/img/push_memory.png
  i18n/zh/docusaurus-plugin-content-blog/2022-10-26-test-report/img/push_total.png
  i18n/zh/docusaurus-plugin-content-blog/2022-10-26-test-report/img/readonly_aggregated_apiserver.png
  i18n/zh/docusaurus-plugin-content-blog/2022-10-26-test-report/img/readonly_cluster.png
  i18n/zh/docusaurus-plugin-content-blog/2022-10-26-test-report/img/readonly_namespace.png
  i18n/zh/docusaurus-plugin-content-blog/2022-10-26-test-report/img/readonly_resource.png
  i18n/zh/docusaurus-plugin-content-blog/2022-10-26-test-report/img/test_architecture.png
  i18n/zh/docusaurus-plugin-content-blog/2022-10-26-test-report/index.md
Labels: kind/documentation, approved, lgtm, size/XL

#238 Fix alignment in working-with-prometheus-in-control-plane.md
  docs/administrator/monitoring/working-with-prometheus-in-control-plane.md
Labels: kind/documentation, approved, lgtm, size/M

#226 update docusaurus to 2.2.0
  docusaurus.config.js
  package-lock.json
  package.json
  src/plugins/faviconCustomPlugin.js
Labels: size/XXL, approved, lgtm

#236 Update adopter use case: Hurricane Engines
  docs/casestudies/adopters.md
  i18n/zh/docusaurus-plugin-content-docs/current/casestudies/adopters.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.3.0/casestudies/adopters.md
  versioned_docs/version-v1.3.0/casestudies/adopters.md
Labels: kind/cleanup, approved, lgtm, size/M

#237 [zh] sync working-with-prometheus-in-control-plane.md
  i18n/zh/docusaurus-plugin-content-docs/current/administrator/monitoring/working-with-prometheus-in-control-plane.md
Labels: kind/documentation, approved, lgtm, size/M

#239 Sync blog to zh
  i18n/zh/docusaurus-plugin-content-blog/2022-03-22-multi-cluster-management-with-an-ocean-of-nodes/img/image1.png
  i18n/zh/docusaurus-plugin-content-blog/2022-03-22-multi-cluster-management-with-an-ocean-of-nodes/img/image2.png
  i18n/zh/docusaurus-plugin-content-blog/2022-03-22-multi-cluster-management-with-an-ocean-of-nodes/img/image3.png
  i18n/zh/docusaurus-plugin-content-blog/2022-03-22-multi-cluster-management-with-an-ocean-of-nodes/img/image4.png
  i18n/zh/docusaurus-plugin-content-blog/2022-03-22-multi-cluster-management-with-an-ocean-of-nodes/img/image5.png
  i18n/zh/docusaurus-plugin-content-blog/2022-03-22-multi-cluster-management-with-an-ocean-of-nodes/index.md
  i18n/zh/docusaurus-plugin-content-blog/2022-09-06-karmada-v1.3/karmada-v1.3.md
  i18n/zh/docusaurus-plugin-content-blog/2022-10-26-test-report/index.md
  i18n/zh/docusaurus-plugin-content-docs/current/installation/installation.md
Labels: kind/documentation, approved, lgtm, size/L

#240 [zh] sync /administrator/upgrading/README.md
  i18n/zh/docusaurus-plugin-content-docs/current/administrator/upgrading/README.md
Labels: kind/documentation, approved, lgtm, size/M

#242 [zh] sync 3 files in /upgrading
  i18n/zh/docusaurus-plugin-content-docs/current/administrator/upgrading/v0.8-v0.9.md
  i18n/zh/docusaurus-plugin-content-docs/current/administrator/upgrading/v0.9-v0.10.md
  i18n/zh/docusaurus-plugin-content-docs/current/administrator/upgrading/v1.2-v1.3.md
Labels: kind/documentation, approved, lgtm, size/S

#244 Add configuring `certRotation` controller
  docs/administrator/configuration/configure-controllers.md
Labels: kind/documentation, approved, lgtm, size/M

#243 [zh] sync files in /upgrading
  i18n/zh/docusaurus-plugin-content-docs/current/administrator/upgrading/v0.10-v1.0.md
  i18n/zh/docusaurus-plugin-content-docs/current/administrator/upgrading/v1.0-v1.1.md
  i18n/zh/docusaurus-plugin-content-docs/current/administrator/upgrading/v1.1-v1.2.md
Labels: kind/documentation, approved, lgtm, size/L

#245 Improve kyverno docs
  docs/userguide/security-governance/working-with-kyverno.md
Labels: kind/documentation, approved, lgtm, size/XL

#241 Improve the summary of the test report
  blog/2022-10-26-test-report/index.md
  i18n/zh/docusaurus-plugin-content-blog/2022-10-26-test-report/index.md
Labels: kind/documentation, approved, lgtm, size/M

#248 [zh] sync /contributor/lifted.md
  i18n/zh/docusaurus-plugin-content-docs/current/contributor/lifted.md
Labels: kind/documentation, approved, lgtm, size/M

#247 Fix format error
  blog/2022-10-26-test-report/index.md
  docs/developers/performance-test-setup-for-karmada.md
  i18n/zh/docusaurus-plugin-content-blog/2022-10-26-test-report/index.md
Labels: kind/cleanup, approved, lgtm, size/M

#252 Nominate Poor12 and Tingtal as docs owners
  OWNERS
  docs/OWNERS
  i18n/OWNERS
Labels: kind/cleanup, approved, lgtm, size/S

#223 Add troubleshooting for x509 error when install karmada
  docs/troubleshooting/troubleshooting.md
  i18n/zh/docusaurus-plugin-content-docs/current/troubleshooting/troubleshooting.md
Labels: kind/documentation, approved, lgtm, size/S

#249 Add federate resource quota docs
  docs/resources/key-features/unified-resourcequota.drawio
  docs/resources/key-features/unified-resourcequota.png
  docs/userguide/roleseparation/federated-resource-quota.md
  docs/userguide/roleseparation/unified-auth.md
  i18n/zh/docusaurus-plugin-content-docs/current/resources/key-features/unified-resourcequota.drawio
  i18n/zh/docusaurus-plugin-content-docs/current/resources/key-features/unified-resourcequota.png
  i18n/zh/docusaurus-plugin-content-docs/current/userguide/roleseparation/federated-resource-quota.md
  i18n/zh/docusaurus-plugin-content-docs/current/userguide/roleseparation/unified-auth.md
  sidebars.js
Labels: kind/documentation, approved, lgtm, size/L

#251 [zh]userguide/network/working-with-submariner.md
  docs/userguide/network/working-with-submariner.md
  i18n/zh/docusaurus-plugin-content-docs/current/userguide/network/working-with-submariner.md
Labels: kind/documentation, approved, lgtm, size/M

#255 Add troubleshooting about "too many open files"
  docs/troubleshooting/troubleshooting.md
Labels: kind/documentation, approved, lgtm, size/S

#256 Update karmadactl init output
  docs/installation/installation.md
  i18n/zh/docusaurus-plugin-content-docs/current/installation/installation.md
Labels: kind/documentation, approved, lgtm, size/M

#259 Add docs about skip ns propagation and PropagationPolicy/ClusterPropagationPolicy priority
  docs/reference/object-association-mapping.md
  docs/userguide/scheduling/namespace-management.md
  docs/userguide/scheduling/resource-propagating.md
  i18n/zh/docusaurus-plugin-content-docs/current/reference/object-association-mapping.md
  i18n/zh/docusaurus-plugin-content-docs/current/userguide/scheduling/namespace-management.md
  i18n/zh/docusaurus-plugin-content-docs/current/userguide/scheduling/resource-propagating.md
  sidebars.js
Labels: kind/documentation, approved, lgtm, size/XL

#261 evolute PropagateDeps FeatureGate to Beta and enable it by default
  docs/installation/install-binary.md
  docs/userguide/scheduling/cluster-resources.md
  docs/userguide/scheduling/propagate-dependencies.md
  i18n/zh/docusaurus-plugin-content-docs/current/installation/install-binary.md
  i18n/zh/docusaurus-plugin-content-docs/current/userguide/scheduling/cluster-resources.md
  i18n/zh/docusaurus-plugin-content-docs/current/userguide/scheduling/propagate-dependencies.md
Labels: kind/documentation, approved, lgtm, size/S, kind/failing-test

#257 Add tutorials about karmada-search
  docs/contributor/contribute-docs.md
  docs/resources/key-features/unified-search.drawio
  docs/resources/key-features/unified-search.png
  docs/resources/tutorials/opensearch.png
  docs/tutorials/karmada-search.md
  docs/userguide/globalview/global-search-for-resources.md
  i18n/zh/docusaurus-plugin-content-docs/current/contributor/contribute-docs.md
  i18n/zh/docusaurus-plugin-content-docs/current/resources/key-features/unified-search.drawio
  i18n/zh/docusaurus-plugin-content-docs/current/resources/key-features/unified-search.png
  i18n/zh/docusaurus-plugin-content-docs/current/resources/tutorials/opensearch.png
  i18n/zh/docusaurus-plugin-content-docs/current/tutorials/karmada-search.md
  i18n/zh/docusaurus-plugin-content-docs/current/userguide/globalview/global-search-for-resources.md
  sidebars.js
Labels: kind/documentation, approved, lgtm, size/XL

#254 Add crd application tutorial
  docs/tutorials/crd-application.md
  i18n/zh/docusaurus-plugin-content-docs/current/tutorials/crd-application.md
  sidebars.js
Labels: kind/documentation, approved, lgtm, size/L

#262 Evolute the reset feature gate to Beta
  docs/installation/install-binary.md
  docs/userguide/failover/failover-overview.md
  docs/userguide/scheduling/cluster-resources.md
  i18n/zh/docusaurus-plugin-content-docs/current/installation/install-binary.md
  i18n/zh/docusaurus-plugin-content-docs/current/userguide/failover/failover-overview.md
  i18n/zh/docusaurus-plugin-content-docs/current/userguide/scheduling/cluster-resources.md
Labels: kind/documentation, approved, lgtm, size/S

#253 [zh] sync /get-started/nginx-example.md
  i18n/zh/docusaurus-plugin-content-docs/current/get-started/nginx-example.md
Labels: kind/documentation, approved, lgtm, size/M

#260 Add metrics and event docs
  docs/reference/instrumentation/event.md
  docs/reference/instrumentation/metrics.md
  i18n/zh/docusaurus-plugin-content-docs/current/reference/instrumentation/event.md
  i18n/zh/docusaurus-plugin-content-docs/current/reference/instrumentation/metrics.md
  sidebars.js
Labels: kind/documentation, approved, lgtm, size/L

#264 [upgrade] add doc for upgrade from 1.3 to 1.4
  docs/administrator/upgrading/README.md
  docs/administrator/upgrading/v1.3-v1.4.md
  i18n/zh/docusaurus-plugin-content-docs/current/administrator/upgrading/README.md
  i18n/zh/docusaurus-plugin-content-docs/current/administrator/upgrading/v1.3-v1.4.md
Labels: kind/documentation, approved, lgtm, size/M

#263 update docs of customizing resource interpreter for declarative
  docs/reference/karmadactl/karmadactl-usage-conventions.md
  docs/userguide/globalview/customizing-resource-interpreter.md
  i18n/zh/docusaurus-plugin-content-docs/current/reference/karmadactl/karmadactl-usage-conventions.md
  i18n/zh/docusaurus-plugin-content-docs/current/userguide/globalview/customizing-resource-interpreter.md
Labels: kind/feature, kind/documentation, approved, lgtm, size/XL
