Repository karmada-io/website, pull requests merged in 2022-08, with the labels that each got.

#124 Doc: add latest kubectl-karmada release suffix comment
  docs/installation/install-kubectl-karmada.md
Labels: size/XS, kind/documentation, approved, lgtm, tide/merge-method-squash

#125 add install-binary and fix some typos
  docs/installation/install-binary.md
  docs/installation/installation.md
  docs/userguide/cicd/working-with-argocd.md
  i18n/zh/docusaurus-plugin-content-docs/current/installation/install-binary.md
  i18n/zh/docusaurus-plugin-content-docs/current/installation/installation.md
  i18n/zh/docusaurus-plugin-content-docs/current/userguide/cicd/working-with-argocd.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.3.0/installation/install-binary.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.3.0/installation/installation.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.3.0/userguide/cicd/working-with-argocd.md
  sidebars.js
  versioned_docs/version-v1.3.0/installation/install-binary.md
  versioned_docs/version-v1.3.0/installation/installation.md
  versioned_docs/version-v1.3.0/userguide/cicd/working-with-argocd.md
  versioned_sidebars/version-v1.3.0-sidebars.json
Labels: size/XXL, kind/cleanup, approved, lgtm

#129 Fix docs error
  docs/resources/istio-on-karmada-different-network.png
  docs/userguide/security-governance/working-with-kyverno.md
  docs/userguide/service/working-with-istio-on-flat-network.md
  docs/userguide/service/working-with-istio-on-non-flat-network.md
  i18n/zh/docusaurus-plugin-content-docs/current/resources/istio-on-karmada-different-network.png
  i18n/zh/docusaurus-plugin-content-docs/current/userguide/security-governance/working-with-kyverno.md
  i18n/zh/docusaurus-plugin-content-docs/current/userguide/service/working-with-istio-on-flat-network.md
  i18n/zh/docusaurus-plugin-content-docs/current/userguide/service/working-with-istio-on-non-flat-network.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.3.0/resources/istio-on-karmada-different-network.png
  i18n/zh/docusaurus-plugin-content-docs/version-v1.3.0/userguide/security-governance/working-with-kyverno.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.3.0/userguide/service/working-with-istio-on-flat-network.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.3.0/userguide/service/working-with-istio-on-non-flat-network.md
  sidebars.js
  versioned_docs/version-v1.3.0/resources/istio-on-karmada-different-network.png
  versioned_docs/version-v1.3.0/userguide/security-governance/working-with-kyverno.md
  versioned_docs/version-v1.3.0/userguide/service/working-with-istio-on-flat-network.md
  versioned_docs/version-v1.3.0/userguide/service/working-with-istio-on-non-flat-network.md
  versioned_sidebars/version-v1.3.0-sidebars.json
Labels: kind/cleanup, approved, lgtm, size/L

#128 update docusaurus link
  README.md
Labels: size/XS, kind/cleanup, approved, lgtm

#132 Add ci123 casestudies.
  i18n/zh/docusaurus-plugin-content-docs/current/casestudies/ci123.md
  i18n/zh/docusaurus-plugin-content-docs/current/resources/adoptions-ci123-architecture.png
  i18n/zh/docusaurus-plugin-content-docs/current/resources/adoptions-ci123-automation-cluster.png
  i18n/zh/docusaurus-plugin-content-docs/current/resources/adoptions-ci123-capability-visualization.png
  i18n/zh/docusaurus-plugin-content-docs/current/resources/adoptions-ci123-cluster-inspection.png
  i18n/zh/docusaurus-plugin-content-docs/current/resources/adoptions-ci123-gpu-resources.png
  i18n/zh/docusaurus-plugin-content-docs/current/resources/adoptions-ci123-msp-multicluster-1.png
  i18n/zh/docusaurus-plugin-content-docs/current/resources/adoptions-ci123-msp-multicluster-2.png
  i18n/zh/docusaurus-plugin-content-docs/current/resources/adoptions-ci123-multicluster-capability.png
  i18n/zh/docusaurus-plugin-content-docs/current/resources/adoptions-ci123-sequence-status.png
  i18n/zh/docusaurus-plugin-content-docs/current/resources/adoptions-ci123-unified-view-1.png
  i18n/zh/docusaurus-plugin-content-docs/current/resources/adoptions-ci123-unified-view-2.png
  i18n/zh/docusaurus-plugin-content-docs/current/resources/adoptions-ci123-velero.png
Labels: approved, lgtm, size/M

#131 fix link error
  docs/administrator/configuration/configure-controllers.md
  docs/administrator/upgrading/v0.10-v1.0.md
  docs/administrator/upgrading/v1.1-v1.2.md
  docs/userguide/cicd/working-with-flux.md
  docs/userguide/network/working-with-submariner.md
  docs/userguide/service/multi-cluster-ingress.md
  docs/userguide/service/working-with-istio-on-non-flat-network.md
  i18n/zh/docusaurus-plugin-content-docs/current/administrator/configuration/configure-controllers.md
  i18n/zh/docusaurus-plugin-content-docs/current/administrator/upgrading/v0.10-v1.0.md
  i18n/zh/docusaurus-plugin-content-docs/current/administrator/upgrading/v1.1-v1.2.md
  i18n/zh/docusaurus-plugin-content-docs/current/userguide/cicd/working-with-flux.md
  i18n/zh/docusaurus-plugin-content-docs/current/userguide/network/working-with-submariner.md
  i18n/zh/docusaurus-plugin-content-docs/current/userguide/service/multi-cluster-ingress.md
  i18n/zh/docusaurus-plugin-content-docs/current/userguide/service/working-with-istio-on-non-flat-network.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.3.0/administrator/configuration/configure-controllers.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.3.0/administrator/upgrading/v0.10-v1.0.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.3.0/administrator/upgrading/v1.1-v1.2.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.3.0/userguide/cicd/working-with-flux.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.3.0/userguide/network/working-with-submariner.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.3.0/userguide/service/multi-cluster-ingress.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.3.0/userguide/service/working-with-istio-on-non-flat-network.md
  versioned_docs/version-v1.3.0/administrator/configuration/configure-controllers.md
  versioned_docs/version-v1.3.0/administrator/upgrading/v0.10-v1.0.md
  versioned_docs/version-v1.3.0/administrator/upgrading/v1.1-v1.2.md
  versioned_docs/version-v1.3.0/userguide/cicd/working-with-flux.md
  versioned_docs/version-v1.3.0/userguide/network/working-with-submariner.md
  versioned_docs/version-v1.3.0/userguide/service/multi-cluster-ingress.md
  versioned_docs/version-v1.3.0/userguide/service/working-with-istio-on-non-flat-network.md
Labels: kind/cleanup, approved, lgtm, size/M

#136 Update picture links and upload missing pictures
  i18n/zh/docusaurus-plugin-content-docs/current/casestudies/ci123.md
  i18n/zh/docusaurus-plugin-content-docs/current/resources/adoptions-ci123-aries.png
  i18n/zh/docusaurus-plugin-content-docs/current/resources/adoptions-ci123-override.png
Labels: size/XS, kind/cleanup, approved, lgtm

#137 Fix broken links for v1.3.0
  i18n/zh/docusaurus-plugin-content-docs/version-v1.3.0/administrator/upgrading/v0.10-v1.0.md
Labels: size/XS, kind/cleanup, approved, lgtm

#138 Add migration path for Kubefed
  docs/administrator/migration/migration-from-kubefed.md
  sidebars.js
  versioned_docs/version-v1.3.0/administrator/migration/migration-from-kubefed.md
  versioned_sidebars/version-v1.3.0-sidebars.json
Labels: kind/documentation, approved, lgtm, size/L

#135 [docs] Add proxy user guide
  docs/userguide/globalview/proxy-global-resource.md
Labels: kind/documentation, approved, lgtm, size/M

#140 change error from NotFound to MethodNotSupported
  docs/userguide/globalview/proxy-global-resource.md
Labels: size/XS, kind/documentation, approved, lgtm

#141 Update dependencies version
  netlify.toml
  package-lock.json
  package.json
  src/components/featuresList.js
Labels: kind/feature, size/XXL, kind/cleanup, approved, lgtm

#142 Introduces the new optional controllers
  docs/administrator/configuration/configure-controllers.md
Labels: kind/documentation, approved, lgtm, size/M

#143 Add a new way of registering cluster with PULL mode by CLI
  docs/userguide/clustermanager/cluster-registration.md
Labels: kind/documentation, approved, lgtm, size/M

#146 suprpress broken links
  docusaurus.config.js
  i18n/zh/docusaurus-plugin-content-docs/current/userguide/globalview/proxy-global-resource.md
  sidebars.js
Labels: kind/cleanup, approved, lgtm, size/M

#139 add cluster resource models docs
  docs/userguide/scheduling/cluster-resources.md
  docs/userguide/scheduling/propagate-dependencies.md
  i18n/zh/docusaurus-plugin-content-docs/current/userguide/scheduling/propagate-dependencies.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.3.0/userguide/scheduling/propagate-dependencies.md
  sidebars.js
  versioned_docs/version-v1.3.0/userguide/scheduling/propagate-dependencies.md
Labels: kind/feature, approved, lgtm, size/L

#147 ignore .idea folder
  .gitignore
Labels: size/XS, kind/cleanup, approved, lgtm

#144 add working-with-prometheus-in-control-plane
  docs/administrator/monitoring/working-with-prometheus-in-control-plane.md
  docs/resources/grafana.png
  sidebars.js
Labels: kind/documentation, approved, lgtm, size/L

#152 Upgrade tar to version 6.1.9
  package-lock.json
Labels: size/XS, kind/cleanup, approved, lgtm

#150 Add English usecase for AIML INSTITUTE
  docs/casestudies/ci123.md
  docs/resources/adoptions-ci123-architecture.png
  docs/resources/adoptions-ci123-aries.png
  docs/resources/adoptions-ci123-automation-cluster.png
  docs/resources/adoptions-ci123-capability-visualization.png
  docs/resources/adoptions-ci123-cluster-inspection.png
  docs/resources/adoptions-ci123-gpu-resources.png
  docs/resources/adoptions-ci123-msp-multicluster-1.png
  docs/resources/adoptions-ci123-msp-multicluster-2.png
  docs/resources/adoptions-ci123-multicluster-capability.png
  docs/resources/adoptions-ci123-override.png
  docs/resources/adoptions-ci123-sequence-status.png
  docs/resources/adoptions-ci123-unified-view-1.png
  docs/resources/adoptions-ci123-unified-view-2.png
  docs/resources/adoptions-ci123-velero.png
  sidebars.js
Labels: kind/documentation, approved, lgtm, size/L

#153 update the failover document
  docs/userguide/failover/failover.md
  i18n/zh/docusaurus-plugin-content-docs/current/userguide/failover/failover.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.3.0/userguide/failover/failover.md
  versioned_docs/version-v1.3.0/userguide/failover/failover.md
Labels: kind/feature, kind/documentation, approved, lgtm, size/XL
