Repository karmada-io/website, pull requests merged in 2022-09, with the labels that each got.

#148 add upgrade document for upgrading from 1.2 to 1.3
  docs/administrator/upgrading/README.md
  docs/administrator/upgrading/v1.2-v1.3.md
  i18n/zh/docusaurus-plugin-content-docs/current/administrator/upgrading/README.md
  i18n/zh/docusaurus-plugin-content-docs/current/administrator/upgrading/v1.2-v1.3.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.3.0/administrator/upgrading/README.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.3.0/administrator/upgrading/v1.2-v1.3.md
  sidebars.js
  versioned_docs/version-v1.3.0/administrator/upgrading/README.md
  versioned_docs/version-v1.3.0/administrator/upgrading/v1.2-v1.3.md
  versioned_sidebars/version-v1.3.0-sidebars.json
Labels: kind/documentation, approved, lgtm, size/M

#154 Add resource model docs in Chinese
  docs/userguide/scheduling/cluster-resources.md
  i18n/zh/docusaurus-plugin-content-docs/current/userguide/scheduling/cluster-resources.md
Labels: kind/documentation, approved, lgtm, size/L

#159 SEL-ZJU Logo Commit
  src/data/supporters.js
  static/img/supporters/SEL-ZJU.png
Labels: size/XS, approved, lgtm, kind/flake

#158 Update dependencies
  package-lock.json
  package.json
Labels: kind/feature, approved, lgtm, size/XL

#160 Add adopters for Karmada
  adopters/README.md
  docs/casestudies/adopters.md
  i18n/zh/docusaurus-plugin-content-docs/current/casestudies/adopters.md
  sidebars.js
Labels: kind/documentation, approved, lgtm, size/M

#169 Fix doc format
  docs/userguide/failover/failover.md
  docs/userguide/scheduling/resource-propagating.md
  i18n/zh/docusaurus-plugin-content-docs/current/userguide/failover/failover.md
  i18n/zh/docusaurus-plugin-content-docs/current/userguide/scheduling/resource-propagating.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.3.0/userguide/failover/failover.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.3.0/userguide/scheduling/resource-propagating.md
  versioned_docs/version-v1.3.0/userguide/failover/failover.md
  versioned_docs/version-v1.3.0/userguide/scheduling/resource-propagating.md
Labels: kind/documentation, approved, lgtm, size/S

#171 Enable documentation search
  docusaurus.config.js
Labels: kind/feature, size/XS, approved, lgtm

#173 remove unnecessary dependencies
  package-lock.json
  package.json
  src/components/featuresList.js
  src/pages/index.js
Labels: size/XXL, kind/cleanup, approved, lgtm

#175 Add missed controllers
  docs/administrator/configuration/configure-controllers.md
  i18n/zh/docusaurus-plugin-content-docs/current/administrator/configuration/configure-controllers.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.3.0/administrator/configuration/configure-controllers.md
  versioned_docs/version-v1.3.0/administrator/configuration/configure-controllers.md
Labels: kind/cleanup, approved, lgtm, size/L

#177 Add youzan to karmada adopters
  docs/casestudies/adopters.md
  i18n/zh/docusaurus-plugin-content-docs/current/casestudies/adopters.md
Labels: size/XS, kind/documentation, approved, lgtm

#178 Update istio-on-nonflat-network docs
  docs/userguide/service/working-with-istio-on-non-flat-network.md
  i18n/zh/docusaurus-plugin-content-docs/current/userguide/service/working-with-istio-on-non-flat-network.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.3.0/userguide/service/working-with-istio-on-non-flat-network.md
  versioned_docs/version-v1.3.0/userguide/service/working-with-istio-on-non-flat-network.md
Labels: kind/documentation, approved, lgtm, size/XL

#179 update .gitignore to remove default generate directory
  .gitignore
Labels: size/XS, approved, lgtm

#180 add trip.com to karmada adopters
  docs/casestudies/adopters.md
  i18n/zh/docusaurus-plugin-content-docs/current/casestudies/adopters.md
Labels: size/XS, kind/documentation, approved, lgtm

#162 Add docs `userguide`
  i18n/zh/docusaurus-plugin-content-docs/current/userguide/service/multi-cluster-service.md
Labels: kind/documentation, approved, lgtm, size/M

#185 put ZHEJIANG LAB to supporter list
  src/data/supporters.js
  static/img/supporters/zhejianglab.png
Labels: size/XS, approved, lgtm, kind/flake

#155 Add the document for failover overview
  docs/resources/userguide/failover/failover-overview.png
  docs/userguide/failover/determine-cluster-failures.md
  docs/userguide/failover/failover-analysis.md
  docs/userguide/failover/failover-overview.md
  docs/userguide/scheduling/resource-propagating.md
  i18n/zh/docusaurus-plugin-content-docs/current/resources/userguide/failover/failover-overview.png
  i18n/zh/docusaurus-plugin-content-docs/current/userguide/failover/determine-cluster-failures.md
  i18n/zh/docusaurus-plugin-content-docs/current/userguide/failover/failover-analysis.md
  i18n/zh/docusaurus-plugin-content-docs/current/userguide/failover/failover-overview.md
  i18n/zh/docusaurus-plugin-content-docs/current/userguide/failover/failover.md
  i18n/zh/docusaurus-plugin-content-docs/current/userguide/scheduling/resource-propagating.md
  sidebars.js
Labels: kind/feature, kind/documentation, approved, lgtm, size/XL

#183 Add key feature doc
  docs/key-features/features.md
  docs/resources/key-features/cluster-failover.png
  docs/resources/key-features/overall-relationship.png
  docs/resources/key-features/overall-rescheduling.png
  docs/resources/key-features/overall-scheduling.png
  docs/resources/key-features/service-governance.png
  docs/resources/key-features/unified-access.png
  docs/resources/key-features/unified-operation.png
  docs/resources/key-features/unified-resourcequota.png
  docs/resources/key-features/unified-search.png
  i18n/zh/docusaurus-plugin-content-docs/current/key-features/features.md
  i18n/zh/docusaurus-plugin-content-docs/current/resources/key-features/cluster-failover.png
  i18n/zh/docusaurus-plugin-content-docs/current/resources/key-features/overall-relationship.png
  i18n/zh/docusaurus-plugin-content-docs/current/resources/key-features/overall-rescheduling.png
  i18n/zh/docusaurus-plugin-content-docs/current/resources/key-features/overall-scheduling.png
  i18n/zh/docusaurus-plugin-content-docs/current/resources/key-features/service-governance.png
  i18n/zh/docusaurus-plugin-content-docs/current/resources/key-features/unified-access.png
  i18n/zh/docusaurus-plugin-content-docs/current/resources/key-features/unified-operation.png
  i18n/zh/docusaurus-plugin-content-docs/current/resources/key-features/unified-resourcequota.png
  i18n/zh/docusaurus-plugin-content-docs/current/resources/key-features/unified-search.png
Labels: kind/documentation, approved, lgtm, size/L

#188 Update adopters add new company.
  docs/casestudies/adopters.md
Labels: size/XS, kind/documentation, approved, lgtm

#170 modify install-binary.md
  docs/installation/install-binary.md
  docs/resources/installation/install-binary/generate_cert/csr_config/admin.conf
  docs/resources/installation/install-binary/generate_cert/csr_config/etcd/apiserver-etcd-client.conf
  docs/resources/installation/install-binary/generate_cert/csr_config/etcd/healthcheck-client.conf
  docs/resources/installation/install-binary/generate_cert/csr_config/etcd/peer.conf
  docs/resources/installation/install-binary/generate_cert/csr_config/etcd/server.conf
  docs/resources/installation/install-binary/generate_cert/csr_config/front-proxy-client.conf
  docs/resources/installation/install-binary/generate_cert/csr_config/karmada.conf
  docs/resources/installation/install-binary/generate_cert/csr_config/kube-apiserver.conf
  docs/resources/installation/install-binary/generate_cert/csr_config/kube-controller-manager.conf
  docs/resources/installation/install-binary/generate_cert/generate_ca.sh
  docs/resources/installation/install-binary/generate_cert/generate_etcd.sh
  docs/resources/installation/install-binary/generate_cert/generate_leaf.sh
  docs/resources/installation/install-binary/generate_cert/util.sh
  docs/resources/installation/install-binary/other_scripts/check_status.sh
  docs/resources/installation/install-binary/other_scripts/create_kubeconfig_file.sh
Labels: size/XXL, kind/documentation, approved, lgtm

#151 add karmada performance testing process
  docs/developers/performance-test-setup-for-karmada.md
  docs/resources/developers/grafana_metrics.png
  sidebars.js
Labels: kind/documentation, approved, lgtm, size/L

#190 Add more sections to install-binary.md
  docs/installation/install-binary.md
  docs/resources/installation/install-binary/other_scripts/check_status.sh
  docs/userguide/scheduling/scheduler-estimator.md
Labels: kind/documentation, approved, lgtm, size/L
