Repository karmada-io/website, pull requests merged in 2023-06, with the labels that each got.

#362 Add document for ClusterAffinities introduction
  docs/userguide/scheduling/resource-propagating.md
  i18n/zh/docusaurus-plugin-content-docs/current/userguide/scheduling/resource-propagating.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.5/userguide/scheduling/resource-propagating.md
  versioned_docs/version-v1.5/userguide/scheduling/resource-propagating.md
Labels: kind/documentation, approved, lgtm, size/L

#363 Add document for upgrading from 1.5 to 1.6
  docs/administrator/upgrading/README.md
  docs/administrator/upgrading/v1.5-v1.6.md
  i18n/zh/docusaurus-plugin-content-docs/current/administrator/upgrading/README.md
  i18n/zh/docusaurus-plugin-content-docs/current/administrator/upgrading/v1.5-v1.6.md
  sidebars.js
Labels: kind/documentation, approved, lgtm, size/M

#364 Update installation.md
  docs/installation/installation.md
Labels: size/XS, kind/documentation, approved, lgtm

#358 Add eriecanal integration doc
  docs/key-features/features.md
  docs/resources/userguide/service/eriecanal/flomesh.sh
  docs/resources/userguide/service/eriecanal/karmada-working-with-eriecanal-overview.png
  docs/userguide/service/working-with-eriecanal.md
  i18n/zh/docusaurus-plugin-content-docs/current/key-features/features.md
  i18n/zh/docusaurus-plugin-content-docs/current/resources/userguide/service/eriecanal/flomesh.sh
  i18n/zh/docusaurus-plugin-content-docs/current/resources/userguide/service/eriecanal/karmada-working-with-eriecanal-overview.png
  i18n/zh/docusaurus-plugin-content-docs/current/userguide/service/working-with-eriecanal.md
  sidebars.js
Labels: size/XXL, kind/documentation, approved, lgtm

#367 Add karmada operator in installation
  docs/installation/installation.md
  i18n/zh/docusaurus-plugin-content-docs/current/installation/installation.md
Labels: size/XS, kind/documentation, approved, lgtm

#365 doc: Add the limitation notes of search proxy
  docs/installation/install-binary.md
  docs/userguide/globalview/global-search-for-resources.md
  i18n/zh/docusaurus-plugin-content-docs/current/installation/install-binary.md
  i18n/zh/docusaurus-plugin-content-docs/current/userguide/globalview/global-search-for-resources.md
Labels: kind/documentation, approved, lgtm, size/S

#368 doc: Add federatedhpa user guide doc
  docs/resources/tutorials/federatedhpa-demo.png
  docs/resources/userguide/autoscaling/federatedhpa-architecture.png
  docs/resources/userguide/autoscaling/federatedhpa-overview.png
  docs/tutorials/autoscaling-with-federatedhpa.md
  docs/userguide/autoscaling/federatedhpa.md
  i18n/zh/docusaurus-plugin-content-docs/current/resources/tutorials/federatedhpa-demo.png
  i18n/zh/docusaurus-plugin-content-docs/current/resources/userguide/autoscaling/federatedhpa-architecture.png
  i18n/zh/docusaurus-plugin-content-docs/current/resources/userguide/autoscaling/federatedhpa-overview.png
  i18n/zh/docusaurus-plugin-content-docs/current/tutorials/autoscaling-with-federatedhpa.md
  i18n/zh/docusaurus-plugin-content-docs/current/userguide/autoscaling/federatedhpa.md
  sidebars.js
Labels: kind/documentation, approved, lgtm, size/XL

#369 Add glossary for Karmada
  docs/reference/glossary.md
  i18n/zh/docusaurus-plugin-content-docs/current/reference/glossary.md
  sidebars.js
Labels: kind/documentation, approved, lgtm, size/L

#371 [zh]update installation.md
  i18n/zh/docusaurus-plugin-content-docs/current/installation/installation.md
Labels: size/XS, kind/documentation, approved, lgtm

#372 fix typos
  docs/userguide/failover/application-failover.md
Labels: size/XS, kind/documentation, approved, lgtm

#375 多云案例文章修复排版内容.
  i18n/zh/docusaurus-plugin-content-docs/current/casestudies/ci123.md
  i18n/zh/docusaurus-plugin-content-docs/current/casestudies/daocloud.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.3/casestudies/ci123.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.4/casestudies/ci123.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.5/casestudies/ci123.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.5/casestudies/daocloud.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.6/casestudies/ci123.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.6/casestudies/daocloud.md
Labels: kind/cleanup, approved, lgtm, size/M

#376 Add ZTO to Karmada Adopters
  docs/casestudies/adopters.md
  i18n/zh/docusaurus-plugin-content-docs/current/casestudies/adopters.md
Labels: size/XS, approved, lgtm

#377 Fix typo for ErieCanal.
  docs/userguide/service/working-with-eriecanal.md
  versioned_docs/version-v1.6/userguide/service/working-with-eriecanal.md
Labels: size/XS, kind/cleanup, approved, lgtm

#380 update package.json
  package-lock.json
Labels: size/XXL, kind/cleanup, approved, lgtm

#385 update Chinese code
  i18n/zh/code.json
Labels: kind/design, approved, lgtm, size/S

#387 Fix indentations in en/zh glossary
  docs/reference/glossary.md
  i18n/zh/docusaurus-plugin-content-docs/current/reference/glossary.md
Labels: kind/cleanup, kind/documentation, approved, lgtm, size/M

#390 Update OWNERS
  OWNERS
Labels: size/XS, approved, lgtm

#391 translate crd-application.md
  i18n/zh/docusaurus-plugin-content-docs/current/administrator/backup/working-with-velero.md
  i18n/zh/docusaurus-plugin-content-docs/current/reference/reserved-namespaces.md
  i18n/zh/docusaurus-plugin-content-docs/current/tutorials/crd-application.md
Labels: kind/documentation, approved, lgtm, size/M

#395 update dependencies
  package-lock.json
  package.json
Labels: approved, lgtm, size/S

#386 Fix title header error
  docs/core-concepts/concepts.md
  i18n/zh/docusaurus-plugin-content-docs/current/core-concepts/concepts.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.6/core-concepts/concepts.md
  versioned_docs/version-v1.6/core-concepts/concepts.md
Labels: kind/documentation, approved, lgtm, size/S

#398 Add SINA to Karmada Adopters
  docs/casestudies/adopters.md
  i18n/zh/docusaurus-plugin-content-docs/current/casestudies/adopters.md
Labels: approved, lgtm, size/S

#400 fix typo CLusterLoader2
  docs/developers/performance-test-setup-for-karmada.md
  i18n/zh/docusaurus-plugin-content-docs/current/developers/performance-test-setup-for-karmada.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.4/developers/performance-test-setup-for-karmada.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.5/developers/performance-test-setup-for-karmada.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.6/developers/performance-test-setup-for-karmada.md
  versioned_docs/version-v1.4/developers/performance-test-setup-for-karmada.md
  versioned_docs/version-v1.5/developers/performance-test-setup-for-karmada.md
  versioned_docs/version-v1.6/developers/performance-test-setup-for-karmada.md
Labels: kind/documentation, approved, lgtm, size/S

#399 Request to join the i18n OWNER
  i18n/OWNERS
Labels: size/XS, approved, lgtm

#383 [zh] translate concepts.md
  i18n/zh/docusaurus-plugin-content-docs/current/core-concepts/concepts.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.6/core-concepts/concepts.md
Labels: approved, lgtm, size/M

#393 Translate promote-legacy-workload.md
  i18n/zh/docusaurus-plugin-content-docs/current/administrator/migration/promote-legacy-workload.md
Labels: kind/documentation, approved, lgtm, size/S

#396 Add applicationFailover and federatedHPA to controllers
  docs/administrator/configuration/configure-controllers.md
  i18n/zh/docusaurus-plugin-content-docs/current/administrator/configuration/configure-controllers.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.6/administrator/configuration/configure-controllers.md
  versioned_docs/version-v1.6/administrator/configuration/configure-controllers.md
Labels: kind/documentation, approved, lgtm, size/S

#384 [zh] translate all core-concepts docs.
  i18n/zh/docusaurus-plugin-content-docs/current/core-concepts/architecture.md
  i18n/zh/docusaurus-plugin-content-docs/current/core-concepts/introduction.md
Labels: kind/documentation, approved, lgtm, size/M

#403 add shopee to karmada adopters
  docs/casestudies/adopters.md
  i18n/zh/docusaurus-plugin-content-docs/current/casestudies/adopters.md
Labels: size/XS, approved, lgtm

#401 [zh]modify docs format
  docs/key-features/features.md
  i18n/zh/docusaurus-plugin-content-docs/current/key-features/features.md
Labels: approved, lgtm, size/M
