Repository karmada-io/website, pull requests merged in 2023-08, with the labels that each got.

#378 Add custom metrics for FederatedHPA
  docs/resources/tutorials/custom_metrics.png
  docs/tutorials/autoscaling-with-custom-metrics.md
  docs/userguide/autoscaling/federatedhpa.md
  i18n/zh/docusaurus-plugin-content-docs/current/resources/tutorials/custom_metrics.png
  i18n/zh/docusaurus-plugin-content-docs/current/tutorials/autoscaling-with-custom-metrics.md
  i18n/zh/docusaurus-plugin-content-docs/current/userguide/autoscaling/federatedhpa.md
  sidebars.js
Labels: kind/documentation, approved, lgtm, size/XL

#441 Add kubeconfig in unified auth
  docs/userguide/bestpractices/unified-auth.md
  i18n/zh/docusaurus-plugin-content-docs/current/userguide/bestpractices/unified-auth.md
Labels: size/XS, kind/documentation, approved, lgtm

#440 Add TaintClusterSucceed and update TaintClusterFailed
  docs/reference/instrumentation/event.md
Labels: size/XS, kind/documentation, approved, lgtm

#446 Update package-lock.json after upgrading dependencies
  package-lock.json
Labels: size/XXL, kind/cleanup, approved, lgtm

#435 doc: Add CronFederatedHPA userguide/tutorials
  docs/resources/userguide/autoscaling/autoscaling-conflicts.png
  docs/resources/userguide/autoscaling/cronfederatedhpa-architecture.png
  docs/tutorials/autoscaling-federatedhpa-with-cronfederatedhpa.md
  docs/tutorials/autoscaling-workload-with-cronfederatedhpa.md
  docs/userguide/autoscaling/cronfederatedhpa.md
  i18n/zh/docusaurus-plugin-content-docs/current/resources/userguide/autoscaling/autoscaling-conflicts.png
  i18n/zh/docusaurus-plugin-content-docs/current/resources/userguide/autoscaling/cronfederatedhpa-architecture.png
  i18n/zh/docusaurus-plugin-content-docs/current/tutorials/autoscaling-federatedhpa-with-cronfederatedhpa.md
  i18n/zh/docusaurus-plugin-content-docs/current/tutorials/autoscaling-workload-with-cronfederatedhpa.md
  i18n/zh/docusaurus-plugin-content-docs/current/userguide/autoscaling/cronfederatedhpa.md
  sidebars.js
Labels: kind/documentation, approved, lgtm, size/XL

#447 added ingress to interpret dependency
  docs/userguide/globalview/customizing-resource-interpreter.md
  i18n/zh/docusaurus-plugin-content-docs/current/userguide/globalview/customizing-resource-interpreter.md
Labels: size/XS, approved, lgtm

#443 Karmada Highly Available Topology Overview
  docs/installation/ha-installation.md
  docs/resources/general/karmada-external-etcd.png
  docs/resources/general/karmada-stacked-etcd.png
  sidebars.js
Labels: kind/documentation, approved, lgtm, size/M

#452 docs: add pod to InterpretReplica support list
  docs/userguide/globalview/customizing-resource-interpreter.md
  i18n/zh/docusaurus-plugin-content-docs/current/userguide/globalview/customizing-resource-interpreter.md
Labels: size/XS, kind/documentation, approved, lgtm

#449 add cosign verify images doc
  docs/administrator/verify-artifacts.md
  i18n/zh/docusaurus-plugin-content-docs/current/administrator/verify-artifacts.md
  sidebars.js
Labels: kind/documentation, approved, lgtm, size/L

#445 [zh] Fix and improve determine cluster failures
  i18n/zh/docusaurus-plugin-content-docs/current/userguide/failover/determine-cluster-failures.md
Labels: kind/documentation, approved, lgtm, size/M

#454 qihoo 360 user story
  docs/casestudies/adopters.md
  i18n/zh/docusaurus-plugin-content-docs/current/casestudies/adopters.md
Labels: size/XS, kind/documentation, approved, lgtm

#456 tidy adopter list
  docs/casestudies/adopters.md
  src/pages/adopters.md
Labels: kind/cleanup, approved, lgtm, size/M

#450 enable clusterrole-aggregation controller
  docs/administrator/configuration/configure-controllers.md
  i18n/zh/docusaurus-plugin-content-docs/current/administrator/configuration/configure-controllers.md
Labels: kind/feature, kind/documentation, approved, lgtm, size/L

#455 add new metrics
  docs/reference/instrumentation/metrics.md
Labels: kind/cleanup, approved, lgtm, size/M

#431 doc: migrate existing resource from a cluster to karmada
  docs/administrator/migration/migrate-in-batch.md
  docs/resources/administrator/migrate-in-batch-1.jpg
  docs/resources/administrator/migrate-in-batch-2.jpg
  docs/tutorials/resource-migration.md
  sidebars.js
Labels: kind/documentation, approved, lgtm, size/L

#457 Translate adopters
  i18n/zh/docusaurus-plugin-content-pages/adopters.md
Labels: kind/cleanup, approved, lgtm, size/M
