Repository karmada-io/website, pull requests merged in 2023-05, with the labels that each got.

#353 doc: update Recommended usage conventions for karmadactl, and fix a t…
  docs/administrator/configuration/configure-controllers.md
  docs/reference/karmadactl/karmadactl-usage-conventions.md
  i18n/zh/docusaurus-plugin-content-docs/current/administrator/configuration/configure-controllers.md
  i18n/zh/docusaurus-plugin-content-docs/current/reference/karmadactl/karmadactl-usage-conventions.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.3/administrator/configuration/configure-controllers.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.4/administrator/configuration/configure-controllers.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.4/reference/karmadactl/karmadactl-usage-conventions.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.5/administrator/configuration/configure-controllers.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.5/reference/karmadactl/karmadactl-usage-conventions.md
  versioned_docs/version-v1.3/administrator/configuration/configure-controllers.md
  versioned_docs/version-v1.4/administrator/configuration/configure-controllers.md
  versioned_docs/version-v1.4/reference/karmadactl/karmadactl-usage-conventions.md
  versioned_docs/version-v1.5/administrator/configuration/configure-controllers.md
  versioned_docs/version-v1.5/reference/karmadactl/karmadactl-usage-conventions.md
Labels: kind/documentation, approved, lgtm, size/L

#357 update dependencies
  package-lock.json
  package.json
Labels: kind/feature, size/XXL, approved, lgtm

#355 update the description of duplicate schedule type in failover-analysis
  docs/userguide/failover/failover-analysis.md
  i18n/zh/docusaurus-plugin-content-docs/current/userguide/failover/failover-analysis.md
Labels: size/XS, kind/cleanup, approved, lgtm

#359 fix redundance kubectl.
  docs/developers/customize-karmada-scheduler.md
  i18n/zh/docusaurus-plugin-content-docs/current/developers/customize-karmada-scheduler.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.5/developers/customize-karmada-scheduler.md
  versioned_docs/version-v1.5/developers/customize-karmada-scheduler.md
Labels: size/XS, kind/cleanup, approved, lgtm

#354 Add application failover doc
  docs/userguide/failover/application-failover.md
  i18n/zh/docusaurus-plugin-content-docs/current/userguide/failover/application-failover.md
  sidebars.js
Labels: kind/documentation, approved, lgtm, size/L

#360 docs: update the document to explain the usage of build-in functions …
  docs/userguide/globalview/customizing-resource-interpreter.md
  i18n/zh/docusaurus-plugin-content-docs/current/userguide/globalview/customizing-resource-interpreter.md
Labels: kind/documentation, approved, lgtm, size/XL

#361 Update the Note of register doc to support general installation
  docs/userguide/clustermanager/cluster-registration.md
Labels: size/XS, kind/cleanup, approved, lgtm

#333 Add casestudy for hurricane-engine
  docs/casestudies/hurricane_engine.md
  i18n/zh/docusaurus-plugin-content-docs/current/casestudies/hurricane_engine.md
  i18n/zh/docusaurus-plugin-content-docs/current/resources/casestudies/hurricane-engine/cluster_inspect.png
  i18n/zh/docusaurus-plugin-content-docs/current/resources/casestudies/hurricane-engine/decentralized_architecture.png
  i18n/zh/docusaurus-plugin-content-docs/current/resources/casestudies/hurricane-engine/eventually_consistency.png
  i18n/zh/docusaurus-plugin-content-docs/current/resources/casestudies/hurricane-engine/gpu_resource_manage.png
  i18n/zh/docusaurus-plugin-content-docs/current/resources/casestudies/hurricane-engine/orang_architecture.png
  i18n/zh/docusaurus-plugin-content-docs/current/resources/casestudies/hurricane-engine/sequence_status.png
  i18n/zh/docusaurus-plugin-content-docs/current/resources/casestudies/hurricane-engine/workload_control.png
  sidebars.js
Labels: kind/documentation, approved, lgtm, size/L
