Repository karmada-io/website, pull requests merged in 2023-09, with the labels that each got.

#464 Add Netease to adopters
  i18n/zh/docusaurus-plugin-content-pages/adopters.md
  src/pages/adopters.md
Labels: size/XS, kind/documentation, approved, lgtm

#463 [zh] translate docs: migrate existing resource
  i18n/zh/docusaurus-plugin-content-docs/current/administrator/migration/migrate-in-batch.md
  i18n/zh/docusaurus-plugin-content-docs/current/resources/administrator/migrate-in-batch-1.jpg
  i18n/zh/docusaurus-plugin-content-docs/current/resources/administrator/migrate-in-batch-2.jpg
  i18n/zh/docusaurus-plugin-content-docs/current/tutorials/resource-migration.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.7/administrator/migration/migrate-in-batch.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.7/resources/administrator/migrate-in-batch-1.jpg
  i18n/zh/docusaurus-plugin-content-docs/version-v1.7/resources/administrator/migrate-in-batch-2.jpg
  i18n/zh/docusaurus-plugin-content-docs/version-v1.7/tutorials/resource-migration.md
Labels: kind/documentation, approved, lgtm, size/XL

#462 doc: add Upgrading Instruction for v1.6 to v1.7
  docs/administrator/upgrading/v1.6-v1.7.md
  i18n/zh/docusaurus-plugin-content-docs/current/administrator/upgrading/v1.6-v1.7.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.7/administrator/upgrading/v1.6-v1.7.md
  sidebars.js
  versioned_docs/version-v1.7/administrator/upgrading/v1.6-v1.7.md
  versioned_sidebars/version-v1.7-sidebars.json
Labels: kind/documentation, approved, lgtm, size/L

#458 add performance metrics for FederatedHPA
  docs/reference/instrumentation/metrics.md
  i18n/zh/docusaurus-plugin-content-docs/current/reference/instrumentation/metrics.md
Labels: approved, lgtm, size/M

#467 Fix dependencies lua script bug
  docs/userguide/globalview/customizing-resource-interpreter.md
  i18n/zh/docusaurus-plugin-content-docs/current/userguide/globalview/customizing-resource-interpreter.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.4/reference/karmadactl/karmadactl-usage-conventions.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.5/reference/karmadactl/karmadactl-usage-conventions.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.5/userguide/globalview/customizing-resource-interpreter.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.6/userguide/globalview/customizing-resource-interpreter.md
  versioned_docs/version-v1.4/reference/karmadactl/karmadactl-usage-conventions.md
  versioned_docs/version-v1.5/reference/karmadactl/karmadactl-usage-conventions.md
  versioned_docs/version-v1.5/userguide/globalview/customizing-resource-interpreter.md
  versioned_docs/version-v1.6/userguide/globalview/customizing-resource-interpreter.md
Labels: kind/bug, kind/cleanup, approved, lgtm, size/S

#468 update dependencies
  package-lock.json
  package.json
Labels: approved, lgtm, size/S

#469 fix: missed to update sidebar for migration doc
  versioned_sidebars/version-v1.7-sidebars.json
Labels: kind/bug, approved, lgtm, size/S

#475 update dependencies
  package-lock.json
  package.json
Labels: size/XXL, approved, lgtm

#478 doc: add iscas as adopter
  i18n/zh/docusaurus-plugin-content-pages/adopters.md
  src/pages/adopters.md
Labels: size/XS, kind/documentation, approved, lgtm
