Repository karmada-io/website, pull requests merged in 2023-04, with the labels that each got.

#335 update get token with tom in unified-auth.md
  docs/userguide/bestpractices/unified-auth.md
  i18n/zh/docusaurus-plugin-content-docs/current/userguide/bestpractices/unified-auth.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.5/userguide/bestpractices/unified-auth.md
  versioned_docs/version-v1.5/userguide/bestpractices/unified-auth.md
Labels: kind/cleanup, approved, lgtm, size/M

#344 add document for karmada control-plane cannot generate token for ServiceAccount
  docs/troubleshooting/trouble-shooting.md
  i18n/zh/docusaurus-plugin-content-docs/current/troubleshooting/trouble-shooting.md
Labels: kind/documentation, approved, lgtm, size/S

#346 update dependencies
  package-lock.json
  package.json
Labels: kind/feature, approved, lgtm, size/S

#348 Add Jiajiayue Group to Karmada Adopters
  docs/casestudies/adopters.md
  i18n/zh/docusaurus-plugin-content-docs/current/casestudies/adopters.md
Labels: size/XS, kind/documentation, approved, lgtm, tide/merge-method-squash

#350 add killercoda url for docs
  docs/core-concepts/introduction.md
Labels: size/XS, approved, lgtm

#352 update Chinese version for started with killercoda
  i18n/zh/docusaurus-plugin-content-docs/current/core-concepts/introduction.md
Labels: size/XS, approved, lgtm
