Repository karmada-io/website, pull requests merged in 2023-01, with the labels that each got.

#283 update document for Built-in Interpreter
  docs/userguide/globalview/customizing-resource-interpreter.md
  i18n/zh/docusaurus-plugin-content-docs/current/userguide/globalview/customizing-resource-interpreter.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.4.0/userguide/globalview/customizing-resource-interpreter.md
  versioned_docs/version-v1.4.0/userguide/globalview/customizing-resource-interpreter.md
Labels: kind/documentation, approved, lgtm, size/M

#282 Update working-with-velero.md
  i18n/zh/docusaurus-plugin-content-docs/current/administrator/backup/working-with-velero.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.4.0/administrator/backup/working-with-velero.md
Labels: approved, lgtm, size/L

#284 built-in interpreter support statefulset
  docs/userguide/globalview/customizing-resource-interpreter.md
  i18n/zh/docusaurus-plugin-content-docs/current/userguide/globalview/customizing-resource-interpreter.md
Labels: size/XS, kind/documentation, approved, lgtm

#285 Add prometheus config for karmada-controller-manager
  docs/administrator/monitoring/working-with-prometheus-in-control-plane.md
  i18n/zh/docusaurus-plugin-content-docs/current/administrator/monitoring/working-with-prometheus-in-control-plane.md
Labels: kind/documentation, approved, lgtm, size/M

#288 Update default resource interpreter documents for PodDisruptionBudget
  docs/userguide/globalview/customizing-resource-interpreter.md
  i18n/zh/docusaurus-plugin-content-docs/current/userguide/globalview/customizing-resource-interpreter.md
Labels: size/XS, kind/documentation, approved, lgtm

#289 Add Mafengwo to karmada adopters
  docs/casestudies/adopters.md
  i18n/zh/docusaurus-plugin-content-docs/current/casestudies/adopters.md
Labels: size/XS, approved, lgtm

#290 Add Neen to adopters
  docs/casestudies/adopters.md
  static/img/supporters/neen.png
Labels: size/XS, approved, lgtm

#292 updaete override-policy.md
  docs/userguide/scheduling/override-policy.md
  i18n/zh/docusaurus-plugin-content-docs/current/userguide/scheduling/override-policy.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.3.0/userguide/scheduling/override-policy.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.4.0/userguide/scheduling/override-policy.md
  versioned_docs/version-v1.3.0/userguide/scheduling/override-policy.md
  versioned_docs/version-v1.4.0/userguide/scheduling/override-policy.md
Labels: approved, lgtm, size/L

#286 Add customize karmada scheduler guide
  docs/developers/customize-karmada-scheduler.md
  docs/resources/developers/schedule-process.png
  i18n/zh/docusaurus-plugin-content-docs/current/developers/customize-karmada-scheduler.md
  i18n/zh/docusaurus-plugin-content-docs/current/resources/developers/schedule-process.png
  sidebars.js
Labels: kind/documentation, approved, lgtm, size/L

#295 fix typo of translate
  i18n/zh/docusaurus-plugin-content-docs/current/userguide/bestpractices/namespace-management.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.4.0/userguide/bestpractices/namespace-management.md
Labels: size/XS, kind/documentation, approved, lgtm

#296 update dependencies
  package-lock.json
  package.json
Labels: size/XXL, approved, lgtm
