Repository karmada-io/website, pull requests merged in 2023-11, with the labels that each got.

#502 translate api networking resource
  i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/networking-resources/multi-cluster-ingress-v1alpha1.md
  i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/networking-resources/multi-cluster-service-v1alpha1.md
Labels: kind/documentation, approved, lgtm, size/XL

#506 fix: fix the invalid link in doc
  i18n/zh/docusaurus-plugin-content-docs/current/tutorials/crd-application.md
Labels: size/XS, kind/documentation, approved, lgtm

#507 Add EHang to adopters
  docs/casestudies/adopters.md
Labels: size/XS, kind/documentation, approved, lgtm

#509 Add EHang to adopters
  adopters/README.md
  i18n/zh/docusaurus-plugin-content-pages/adopters.md
  src/pages/adopters.md
Labels: size/XS, kind/documentation, approved, lgtm

#508 Add resource deletion protection user guide
  docs/administrator/configuration/resource-deletion-protection.md
  i18n/zh/docusaurus-plugin-content-docs/current/administrator/configuration/resource-deletion-protection.md
  sidebars.js
Labels: kind/documentation, approved, lgtm, size/L

#511 remove unnecessary docusaurus version in README.md
  README.md
Labels: size/XS, kind/cleanup, approved, lgtm

#512 Add namespace sync FQA
  docs/faq/faq.md
  i18n/zh/docusaurus-plugin-content-docs/current/faq/faq.md
Labels: kind/documentation, approved, lgtm, size/S

#513 Fix break link in FAQ
  docs/faq/faq.md
  i18n/zh/docusaurus-plugin-content-docs/current/faq/faq.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.3/faq/faq.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.4/faq/faq.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.5/faq/faq.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.6/faq/faq.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.7/faq/faq.md
  versioned_docs/version-v1.3/faq/faq.md
  versioned_docs/version-v1.4/faq/faq.md
  versioned_docs/version-v1.5/faq/faq.md
  versioned_docs/version-v1.6/faq/faq.md
  versioned_docs/version-v1.7/faq/faq.md
Labels: kind/bug, kind/cleanup, approved, lgtm, size/S

#514 Add Kuaishou to adopters
  i18n/zh/docusaurus-plugin-content-pages/adopters.md
  src/pages/adopters.md
Labels: size/XS, kind/documentation, approved, lgtm

#516 Translate karmada search document
  docs/tutorials/karmada-search.md
  i18n/zh/docusaurus-plugin-content-docs/current/tutorials/karmada-search.md
Labels: kind/documentation, approved, lgtm, size/M
