Repository karmada-io/website, pull requests merged in 2023-03, with the labels that each got.

#321 Ducumentation for release v1.5 to sync zh
  docs/casestudies/adopters.md
  i18n/zh/docusaurus-plugin-content-docs/current/casestudies/adopters.md
  i18n/zh/docusaurus-plugin-content-docs/current/reference/instrumentation/metrics.md
  i18n/zh/docusaurus-plugin-content-docs/current/resources/userguide/cicd/argocd/argocd-2.6.0-status-overview.png
  i18n/zh/docusaurus-plugin-content-docs/current/userguide/cicd/working-with-argocd.md
Labels: kind/cleanup, kind/documentation, approved, lgtm, size/M

#325 update documentation releasing
  docs/developers/document-releasing.md
  i18n/zh/docusaurus-plugin-content-docs/current/developers/document-releasing.md
Labels: kind/cleanup, approved, lgtm, size/M

#320 update dependencies
  package-lock.json
  package.json
Labels: approved, lgtm, size/S

#329 fix company logo
  static/img/supporters/CECloud.png
Labels: size/XS, kind/cleanup, approved, lgtm

#331 fix wrong translation
  i18n/zh/docusaurus-plugin-content-docs/current/userguide/globalview/customizing-resource-interpreter.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.5/userguide/globalview/customizing-resource-interpreter.md
Labels: size/XS, approved, lgtm

#334 Fix filter interface when customize the scheduler
  docs/developers/customize-karmada-scheduler.md
  i18n/zh/docusaurus-plugin-content-docs/current/developers/customize-karmada-scheduler.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.5/developers/customize-karmada-scheduler.md
  versioned_docs/version-v1.5/developers/customize-karmada-scheduler.md
Labels: kind/cleanup, approved, lgtm, size/M

#327 update Supporters list
  src/css/custom.css
Labels: size/XS, kind/design, approved, lgtm

#339 update doc of built-in Interpreter
  docs/userguide/globalview/customizing-resource-interpreter.md
  i18n/zh/docusaurus-plugin-content-docs/current/userguide/globalview/customizing-resource-interpreter.md
Labels: size/XS, kind/documentation, approved, lgtm

#341 update docusaurus
  package-lock.json
  package.json
Labels: size/XXL, approved, lgtm
