Repository karmada-io/website, pull requests merged in 2023-07, with the labels that each got.

#408 [zh] translate document releasing docs
  i18n/zh/docusaurus-plugin-content-docs/current/developers/document-releasing.md
Labels: kind/documentation, approved, lgtm, size/M

#410 add windsonsea to doc-reviewers
  i18n/OWNERS
Labels: size/XS, kind/documentation, approved, lgtm

#397 translate federatedhpa.md
  docs/userguide/autoscaling/federatedhpa.md
  i18n/zh/docusaurus-plugin-content-docs/current/userguide/autoscaling/federatedhpa.md
Labels: kind/documentation, approved, lgtm, size/M

#416 fix typos
  docs/administrator/backup/working-with-velero.md
  docs/administrator/migration/migration-from-kubefed.md
  docs/administrator/monitoring/working-with-filebeat.md
  docs/contributor/cherry-picks.md
  docs/contributor/contribute-docs.md
  docs/contributor/count-contributions.md
  docs/contributor/lifted.md
  docs/get-started/nginx-example.md
  docs/installation/fromsource.md
  docs/installation/install-binary.md
  docs/installation/install-cli-tools.md
  docs/installation/installation.md
Labels: kind/documentation, approved, lgtm, size/L

#415 Add issue template for tracking missing documents
  .github/ISSUE_TEMPLATE/request-doc.md
Labels: kind/cleanup, approved, lgtm, size/S

#414 add single pages for adopters
  docusaurus.config.js
  i18n/zh/docusaurus-plugin-content-pages/adopters.md
  i18n/zh/docusaurus-theme-classic/footer.json
  i18n/zh/docusaurus-theme-classic/navbar.json
  src/pages/adopters.md
Labels: kind/feature, approved, lgtm, size/L

#405 [zh]translate docs:migration-from-kubefed.md
  docs/administrator/migration/migration-from-kubefed.md
  i18n/zh/docusaurus-plugin-content-docs/current/administrator/migration/migration-from-kubefed.md
Labels: kind/documentation, approved, lgtm, size/L

#394 translate configure-controllers.md
  i18n/zh/docusaurus-plugin-content-docs/current/administrator/configuration/configure-controllers.md
Labels: kind/documentation, approved, lgtm, size/L

#423 Update ResourceBinding label to annotation
  docs/resources/general/object-association-map.drawio
  docs/resources/general/object-association-map.png
Labels: kind/documentation, approved, lgtm, size/L

#420 doc: add core concepts of components
  docs/core-concepts/components.md
  docs/resources/general/components.png
  sidebars.js
Labels: kind/documentation, approved, lgtm, size/L

#424 Update metrics
  docs/reference/instrumentation/metrics.md
  i18n/zh/docusaurus-plugin-content-docs/current/reference/instrumentation/metrics.md
Labels: kind/documentation, approved, lgtm, size/L

#426 [zh] translate docs: components.md
  i18n/zh/docusaurus-plugin-content-docs/current/core-concepts/components.md
  i18n/zh/docusaurus-plugin-content-docs/current/resources/general/components.png
Labels: kind/documentation, approved, lgtm, size/L

#412 [zh] translate docs: aggregated-api-endpoint.md
  i18n/zh/docusaurus-plugin-content-docs/current/userguide/globalview/aggregated-api-endpoint.md
Labels: kind/documentation, approved, lgtm, size/M

#428 Update workload label and annotation
  docs/resources/general/object-association-map.drawio
  docs/resources/general/object-association-map.png
Labels: kind/documentation, approved, lgtm, size/M

#427 Add description for priority of pp and cpp
  docs/userguide/scheduling/resource-propagating.md
  i18n/zh/docusaurus-plugin-content-docs/current/userguide/scheduling/resource-propagating.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.4/userguide/scheduling/resource-propagating.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.5/userguide/scheduling/resource-propagating.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.6/userguide/scheduling/resource-propagating.md
  versioned_docs/version-v1.4/userguide/scheduling/resource-propagating.md
  versioned_docs/version-v1.5/userguide/scheduling/resource-propagating.md
  versioned_docs/version-v1.6/userguide/scheduling/resource-propagating.md
Labels: kind/documentation, approved, lgtm, size/M

#433 doc: update Karmada controller list
  docs/administrator/configuration/configure-controllers.md
  i18n/zh/docusaurus-plugin-content-docs/current/administrator/configuration/configure-controllers.md
Labels: kind/documentation, approved, lgtm, size/M

#434 [zh] translate count-contributions docs
  i18n/zh/docusaurus-plugin-content-docs/current/contributor/count-contributions.md
Labels: kind/documentation, approved, lgtm, size/S
