Repository karmada-io/website, pull requests merged in 2023-12, with the labels that each got.

#521 Translate sibebar items
  i18n/zh/docusaurus-plugin-content-docs/current.json
Labels: kind/documentation, approved, lgtm, size/L

#517 doc: fix typo error in --karmada-data params
  i18n/zh/docusaurus-plugin-content-docs/current/installation/installation.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.7/installation/installation.md
Labels: size/XS, kind/documentation, approved, lgtm

#526 Update adopters.md to remove TBD
  i18n/zh/docusaurus-plugin-content-pages/adopters.md
  src/pages/adopters.md
Labels: kind/documentation, approved, lgtm, size/M

#523 add Upgrading Instruction for v1.7 to v1.8
  docs/administrator/upgrading/v1.7-v1.8.md
  docusaurus.config.js
  sidebars.js
  versioned_docs/version-v1.8/administrator/upgrading/v1.7-v1.8.md
  versioned_sidebars/version-v1.8-sidebars.json
Labels: kind/documentation, approved, lgtm, size/M

#524 Repair broken links and use relative paths to locate resources
  docs/key-features/features.md
  i18n/zh/docusaurus-plugin-content-docs/current/key-features/features.md
Labels: kind/cleanup, approved, lgtm, size/M

#528 add zh Upgrading Instruction for v1.7 to v1.8
  docusaurus.config.js
  i18n/zh/docusaurus-plugin-content-docs/current/administrator/upgrading/v1.7-v1.8.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.8/administrator/upgrading/v1.7-v1.8.md
Labels: kind/documentation, approved, lgtm, size/M

#529 Fix wrong reference website for docs.
  docs/contributor/count-contributions.md
  i18n/zh/docusaurus-plugin-content-docs/current/contributor/count-contributions.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.6/contributor/count-contributions.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.7/contributor/count-contributions.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.8/contributor/count-contributions.md
  versioned_docs/version-v1.6/contributor/count-contributions.md
  versioned_docs/version-v1.7/contributor/count-contributions.md
  versioned_docs/version-v1.8/contributor/count-contributions.md
Labels: kind/documentation, approved, lgtm, size/S

#530 fix: add missing links to Upgrading Instruction
  docs/administrator/upgrading/README.md
  i18n/zh/docusaurus-plugin-content-docs/current/administrator/upgrading/README.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.8/administrator/upgrading/README.md
  versioned_docs/version-v1.8/administrator/upgrading/README.md
Labels: size/XS, kind/documentation, approved, lgtm

#533 add zh doc to karmada event reference
  i18n/zh/docusaurus-plugin-content-docs/current/reference/instrumentation/event.md
Labels: kind/documentation, approved, lgtm, size/S

#534 add zh doc to karmada Metrics reference
  i18n/zh/docusaurus-plugin-content-docs/current/reference/instrumentation/event.md
  i18n/zh/docusaurus-plugin-content-docs/current/reference/instrumentation/metrics.md
Labels: kind/documentation, approved, lgtm, size/M

#535 add Security Considerations document
  docs/administrator/security/security-considerations.md
  docs/administrator/security/verify-artifacts.md
  i18n/zh/docusaurus-plugin-content-docs/current.json
  i18n/zh/docusaurus-plugin-content-docs/current/administrator/security/security-considerations.md
  i18n/zh/docusaurus-plugin-content-docs/current/administrator/security/verify-artifacts.md
  sidebars.js
Labels: kind/documentation, approved, lgtm, size/M

#527 remove redundant adopter pages
  docs/casestudies/adopters.md
  i18n/zh/docusaurus-plugin-content-docs/current/casestudies/adopters.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.3/casestudies/adopters.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.4/casestudies/adopters.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.5/casestudies/adopters.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.6/casestudies/adopters.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.7/casestudies/adopters.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.8/casestudies/adopters.md
  versioned_docs/version-v1.3/casestudies/adopters.md
  versioned_docs/version-v1.4/casestudies/adopters.md
  versioned_docs/version-v1.5/casestudies/adopters.md
  versioned_docs/version-v1.6/casestudies/adopters.md
  versioned_docs/version-v1.7/casestudies/adopters.md
  versioned_docs/version-v1.8/casestudies/adopters.md
Labels: kind/documentation, approved, lgtm, size/L

#536 Add DSK to case study
  i18n/zh/docusaurus-plugin-content-pages/adopters.md
  src/pages/adopters.md
Labels: size/XS, kind/documentation, approved, lgtm

#538 add adopters unionbigdata and BOE
  i18n/zh/docusaurus-plugin-content-pages/adopters.md
  src/pages/adopters.md
Labels: kind/documentation, approved, lgtm, size/M

#539 add zh doc to karmada retain interpreter common problems
  i18n/zh/docusaurus-plugin-content-docs/current/userguide/globalview/customizing-resource-interpreter.md
Labels: kind/documentation, approved, lgtm, size/S

#540 doc: Update sandbox to incubation
  docs/core-concepts/introduction.md
  i18n/zh/docusaurus-plugin-content-docs/current/core-concepts/introduction.md
  src/pages/index.js
Labels: size/XS, kind/documentation, approved, lgtm

#542 doc: add adopter iQIYI
  i18n/zh/docusaurus-plugin-content-pages/adopters.md
  src/pages/adopters.md
Labels: size/XS, kind/documentation, approved, lgtm

#541 add doc about karmada retain interpreter common problems
  docs/userguide/globalview/customizing-resource-interpreter.md
Labels: kind/documentation, approved, lgtm, size/S
