Repository karmada-io/website, pull requests merged in 2023-02, with the labels that each got.

#302 Add multiple scheduler docs
  docs/developers/customize-karmada-scheduler.md
  i18n/zh/docusaurus-plugin-content-docs/current/developers/customize-karmada-scheduler.md
Labels: kind/documentation, approved, lgtm, size/L

#304 update dependencies
  package-lock.json
  package.json
Labels: approved, lgtm, size/XL

#305 Ttranslate custom resource interpreter
  i18n/zh/docusaurus-plugin-content-docs/current/userguide/globalview/customizing-resource-interpreter.md
Labels: kind/documentation, approved, lgtm, size/L

#308 update dependencies
  package-lock.json
  package.json
Labels: approved, lgtm, size/S

#309 add ResourceInterpreterCustomization yaml example
  docs/userguide/globalview/customizing-resource-interpreter.md
  i18n/zh/docusaurus-plugin-content-docs/current/userguide/globalview/customizing-resource-interpreter.md
Labels: kind/cleanup, kind/documentation, approved, lgtm, size/L

#310 Migrate from k8s.gcr.io to registry.k8s.io
  docs/troubleshooting/trouble-shooting.md
  i18n/zh/docusaurus-plugin-content-docs/current/troubleshooting/trouble-shooting.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.3.0/troubleshooting/troubleshooting.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.4.0/troubleshooting/trouble-shooting.md
  versioned_docs/version-v1.3.0/troubleshooting/troubleshooting.md
  versioned_docs/version-v1.4.0/troubleshooting/trouble-shooting.md
Labels: kind/cleanup, approved, lgtm, size/M

#311 Fix google container registry
  docs/troubleshooting/trouble-shooting.md
  i18n/zh/docusaurus-plugin-content-docs/current/troubleshooting/trouble-shooting.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.3.0/troubleshooting/troubleshooting.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.4.0/troubleshooting/trouble-shooting.md
  versioned_docs/version-v1.3.0/troubleshooting/troubleshooting.md
  versioned_docs/version-v1.4.0/troubleshooting/trouble-shooting.md
Labels: kind/documentation, approved, lgtm, size/S

#313 Change theme to github
  docusaurus.config.js
Labels: size/XS, kind/cleanup, approved, lgtm

#314 updaete override-policy fieldSelector
  docs/userguide/scheduling/override-policy.md
  i18n/zh/docusaurus-plugin-content-docs/current/userguide/scheduling/override-policy.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.4.0/userguide/scheduling/override-policy.md
  versioned_docs/version-v1.4.0/userguide/scheduling/override-policy.md
Labels: approved, lgtm, size/L

#312 Give more clear steps about how to install karmada with binaries
  docs/installation/install-binary.md
  i18n/zh/docusaurus-plugin-content-docs/current/installation/install-binary.md
Labels: kind/documentation, approved, lgtm, size/L

#315 add CronJob to build-in AggregateStatus Interpreter
  docs/userguide/globalview/customizing-resource-interpreter.md
  i18n/zh/docusaurus-plugin-content-docs/current/userguide/globalview/customizing-resource-interpreter.md
Labels: size/XS, kind/documentation, approved, lgtm

#316 Add CECloud to adopters
  docs/casestudies/adopters.md
  i18n/zh/docusaurus-plugin-content-docs/current/casestudies/adopters.md
  src/data/supporters.js
  static/img/supporters/CECloud.png
Labels: size/XS, kind/documentation, approved, lgtm

#293 updaete blog title
  blog/2022-09-06-karmada-v1.3/karmada-v1.3.md
Labels: size/XS, approved, lgtm

#278 Add document release docs
  docs/developers/document-releasing.md
  i18n/zh/docusaurus-plugin-content-docs/current/developers/document-releasing.md
  sidebars.js
Labels: kind/documentation, approved, lgtm, size/L

#275 Add daocloud casestudy
  docs/casestudies/ci123.md
  docs/casestudies/daocloud.md
  i18n/zh/docusaurus-plugin-content-docs/current/casestudies/adopters.md
  i18n/zh/docusaurus-plugin-content-docs/current/casestudies/daocloud.md
  i18n/zh/docusaurus-plugin-content-docs/current/resources/casestudies/daocloud/auto_convert.PNG
  i18n/zh/docusaurus-plugin-content-docs/current/resources/casestudies/daocloud/kairship_architecture.PNG
  i18n/zh/docusaurus-plugin-content-docs/current/resources/casestudies/daocloud/karmada_operator.PNG
  i18n/zh/docusaurus-plugin-content-docs/current/resources/casestudies/daocloud/multi_karmada.PNG
  i18n/zh/docusaurus-plugin-content-docs/current/resources/casestudies/daocloud/multi_tenant.PNG
  i18n/zh/docusaurus-plugin-content-docs/current/resources/casestudies/daocloud/prompt.PNG
  i18n/zh/docusaurus-plugin-content-docs/current/resources/casestudies/daocloud/ui.PNG
  sidebars.js
Labels: kind/documentation, approved, lgtm, size/M

#319 Add updating docs(v1.4-v1.5)
  docs/administrator/upgrading/README.md
  docs/administrator/upgrading/v1.4-v1.5.md
  i18n/zh/docusaurus-plugin-content-docs/current/administrator/upgrading/README.md
  i18n/zh/docusaurus-plugin-content-docs/current/administrator/upgrading/v1.4-v1.5.md
  sidebars.js
Labels: kind/documentation, approved, lgtm, size/M
