Repository karmada-io/website, pull requests merged in 2023-10, with the labels that each got.

#481 update dependencies
  package-lock.json
  package.json
Labels: approved, lgtm, size/S

#476 Add API Documents
  docs/reference/karmada-api/auto-scaling-resources/cron-federated-hpa-v1alpha1.md
  docs/reference/karmada-api/auto-scaling-resources/federated-hpa-v1alpha1.md
  docs/reference/karmada-api/cluster-resources/cluster-v1alpha1.md
  docs/reference/karmada-api/common-definitions/delete-options.md
  docs/reference/karmada-api/common-definitions/label-selector.md
  docs/reference/karmada-api/common-definitions/list-meta.md
  docs/reference/karmada-api/common-definitions/node-selector-requirement.md
  docs/reference/karmada-api/common-definitions/object-meta.md
  docs/reference/karmada-api/common-definitions/patch.md
  docs/reference/karmada-api/common-definitions/quantity.md
  docs/reference/karmada-api/common-definitions/status.md
  docs/reference/karmada-api/common-definitions/typed-local-object-reference.md
  docs/reference/karmada-api/common-parameter/common-parameters.md
  docs/reference/karmada-api/config-resources/resource-interpreter-customization-v1alpha1.md
  docs/reference/karmada-api/config-resources/resource-interpreter-webhook-configuration-v1alpha1.md
  docs/reference/karmada-api/networking-resources/multi-cluster-ingress-v1alpha1.md
  docs/reference/karmada-api/networking-resources/multi-cluster-service-v1alpha1.md
  docs/reference/karmada-api/policy-resources/cluster-override-policy-v1alpha1.md
  docs/reference/karmada-api/policy-resources/cluster-propagation-policy-v1alpha1.md
  docs/reference/karmada-api/policy-resources/federated-resource-quota-v1alpha1.md
  docs/reference/karmada-api/policy-resources/override-policy-v1alpha1.md
  docs/reference/karmada-api/policy-resources/propagation-policy-v1alpha1.md
  docs/reference/karmada-api/search-resources/resource-registry-v1alpha1.md
  docs/reference/karmada-api/work-resources/cluster-resource-binding-v1alpha2.md
  docs/reference/karmada-api/work-resources/resource-binding-v1alpha2.md
  docs/reference/karmada-api/work-resources/work-v1alpha1.md
  sidebars.js
Labels: size/XXL, approved, lgtm

#482 auto generate index at sidebar for karmada-api
  sidebars.js
Labels: approved, lgtm, size/M

#484 prepare for Karmada API document translate
  i18n/zh/docusaurus-plugin-content-docs/current.json
  i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/auto-scaling-resources/cron-federated-hpa-v1alpha1.md
  i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/auto-scaling-resources/federated-hpa-v1alpha1.md
  i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/cluster-resources/cluster-v1alpha1.md
  i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/common-definitions/delete-options.md
  i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/common-definitions/label-selector.md
  i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/common-definitions/list-meta.md
  i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/common-definitions/node-selector-requirement.md
  i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/common-definitions/object-meta.md
  i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/common-definitions/patch.md
  i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/common-definitions/quantity.md
  i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/common-definitions/status.md
  i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/common-definitions/typed-local-object-reference.md
  i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/common-parameter/common-parameters.md
  i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/config-resources/resource-interpreter-customization-v1alpha1.md
  i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/config-resources/resource-interpreter-webhook-configuration-v1alpha1.md
  i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/networking-resources/multi-cluster-ingress-v1alpha1.md
  i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/networking-resources/multi-cluster-service-v1alpha1.md
  i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/policy-resources/cluster-override-policy-v1alpha1.md
  i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/policy-resources/cluster-propagation-policy-v1alpha1.md
  i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/policy-resources/federated-resource-quota-v1alpha1.md
  i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/policy-resources/override-policy-v1alpha1.md
  i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/policy-resources/propagation-policy-v1alpha1.md
  i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/search-resources/resource-registry-v1alpha1.md
  i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/work-resources/cluster-resource-binding-v1alpha2.md
  i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/work-resources/resource-binding-v1alpha2.md
  i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/work-resources/work-v1alpha1.md
Labels: size/XXL, kind/documentation, approved, lgtm

#487 Translate Karmada API index description
  i18n/zh/docusaurus-plugin-content-docs/current.json
  sidebars.js
Labels: kind/feature, size/XS, kind/documentation, approved, lgtm

#488 Add cluster API resource faq
  docs/faq/faq.md
  i18n/zh/docusaurus-plugin-content-docs/current/faq/faq.md
Labels: kind/documentation, approved, lgtm, size/S

#489 update karmada-search.md
  docs/tutorials/karmada-search.md
  i18n/zh/docusaurus-plugin-content-docs/current/tutorials/karmada-search.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.4/tutorials/karmada-search.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.5/tutorials/karmada-search.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.6/tutorials/karmada-search.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.7/tutorials/karmada-search.md
  versioned_docs/version-v1.4/tutorials/karmada-search.md
  versioned_docs/version-v1.5/tutorials/karmada-search.md
  versioned_docs/version-v1.6/tutorials/karmada-search.md
  versioned_docs/version-v1.7/tutorials/karmada-search.md
Labels: approved, lgtm, size/S

#465 doc: FederatedHPA docs cleanup
  docs/tutorials/autoscaling-with-resource-metrics.md
  docs/userguide/autoscaling/federatedhpa.md
  i18n/zh/docusaurus-plugin-content-docs/current/tutorials/autoscaling-with-resource-metrics.md
  i18n/zh/docusaurus-plugin-content-docs/current/userguide/autoscaling/federatedhpa.md
  sidebars.js
Labels: kind/cleanup, kind/documentation, approved, lgtm, size/S

#491 update dependencies
  package-lock.json
  package.json
Labels: approved, lgtm, size/S

#492 translate api work resource
  i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/work-resources/cluster-resource-binding-v1alpha2.md
  i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/work-resources/resource-binding-v1alpha2.md
  i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/work-resources/work-v1alpha1.md
Labels: size/XXL, kind/documentation, approved, lgtm

#494 update the chinese translation of propagate
  blog/2022-09-06-karmada-v1.3/karmada-v1.3.md
  i18n/zh/docusaurus-plugin-content-blog/2022-09-06-karmada-v1.3/karmada-v1.3.md
  i18n/zh/docusaurus-plugin-content-docs/current/administrator/backup/working-with-velero.md
  i18n/zh/docusaurus-plugin-content-docs/current/administrator/migration/migrate-in-batch.md
  i18n/zh/docusaurus-plugin-content-docs/current/casestudies/ci123.md
  i18n/zh/docusaurus-plugin-content-docs/current/developers/customize-karmada-scheduler.md
  i18n/zh/docusaurus-plugin-content-docs/current/faq/faq.md
  i18n/zh/docusaurus-plugin-content-docs/current/tutorials/resource-migration.md
  i18n/zh/docusaurus-plugin-content-docs/current/userguide/bestpractices/namespace-management.md
  i18n/zh/docusaurus-plugin-content-docs/current/userguide/failover/failover-analysis.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.3/casestudies/ci123.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.4/administrator/backup/working-with-velero.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.4/casestudies/ci123.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.4/faq/faq.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.4/userguide/bestpractices/namespace-management.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.4/userguide/failover/failover-analysis.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.5/administrator/backup/working-with-velero.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.5/casestudies/ci123.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.5/developers/customize-karmada-scheduler.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.5/faq/faq.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.5/userguide/bestpractices/namespace-management.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.5/userguide/failover/failover-analysis.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.6/administrator/backup/working-with-velero.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.6/casestudies/ci123.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.6/developers/customize-karmada-scheduler.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.6/faq/faq.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.6/userguide/bestpractices/namespace-management.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.6/userguide/failover/failover-analysis.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.7/administrator/backup/working-with-velero.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.7/administrator/migration/migrate-in-batch.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.7/casestudies/ci123.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.7/developers/customize-karmada-scheduler.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.7/faq/faq.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.7/tutorials/resource-migration.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.7/userguide/bestpractices/namespace-management.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.7/userguide/failover/failover-analysis.md
Labels: kind/cleanup, approved, lgtm, size/L

#493 translate api policy resource
  i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/policy-resources/cluster-override-policy-v1alpha1.md
  i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/policy-resources/cluster-propagation-policy-v1alpha1.md
  i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/policy-resources/federated-resource-quota-v1alpha1.md
  i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/policy-resources/override-policy-v1alpha1.md
  i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/policy-resources/propagation-policy-v1alpha1.md
Labels: size/XXL, kind/documentation, approved, lgtm

#497 translate api auto scaling resource
  i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/auto-scaling-resources/cron-federated-hpa-v1alpha1.md
  i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/auto-scaling-resources/federated-hpa-v1alpha1.md
Labels: size/XXL, kind/documentation, approved, lgtm

#498 translate api cluster resource
  i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/cluster-resources/cluster-v1alpha1.md
Labels: kind/documentation, approved, lgtm, size/L

#500 translate api search resource
  i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/search-resources/resource-registry-v1alpha1.md
Labels: kind/documentation, approved, lgtm, size/L

#496 Accessibility add links name to icons
  docusaurus.config.js
Labels: size/XS, approved, lgtm

#501 fix wrong translation of referent word in auto-scaling-resources
  i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/auto-scaling-resources/cron-federated-hpa-v1alpha1.md
  i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/auto-scaling-resources/federated-hpa-v1alpha1.md
Labels: kind/cleanup, approved, lgtm, size/S

#499 translate api config resource
  i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/config-resources/resource-interpreter-customization-v1alpha1.md
  i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/config-resources/resource-interpreter-webhook-configuration-v1alpha1.md
Labels: kind/documentation, approved, lgtm, size/XL

#503 translate api with common definitions
  i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/common-definitions/delete-options.md
  i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/common-definitions/label-selector.md
  i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/common-definitions/list-meta.md
  i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/common-definitions/node-selector-requirement.md
  i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/common-definitions/object-meta.md
  i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/common-definitions/patch.md
  i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/common-definitions/quantity.md
  i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/common-definitions/status.md
  i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/common-definitions/typed-local-object-reference.md
Labels: kind/documentation, approved, lgtm, size/L

#504 translate api with common parameter
  i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/common-parameter/common-parameters.md
Labels: kind/documentation, approved, lgtm, size/L
