Repository karmada-io/website, pull requests merged in 2024-02, with the labels that each got.

#562 update some docs for docusaurus v3
  blog/2022-10-26-test-report/index.md
  docs/contributor/contribute-docs.md
  docs/installation/install-binary.md
  docs/releases.md
  i18n/zh/docusaurus-plugin-content-docs/current/releases.md
Labels: kind/feature, kind/cleanup, kind/documentation, approved, lgtm, size/S

#564 update resource-propagating.md
  docs/userguide/scheduling/resource-propagating.md
  i18n/zh/docusaurus-plugin-content-docs/current/userguide/scheduling/resource-propagating.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.3/userguide/scheduling/resource-propagating.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.4/userguide/scheduling/resource-propagating.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.5/userguide/scheduling/resource-propagating.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.6/userguide/scheduling/resource-propagating.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.7/userguide/scheduling/resource-propagating.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.8/userguide/scheduling/resource-propagating.md
  versioned_docs/version-v1.3/userguide/scheduling/resource-propagating.md
  versioned_docs/version-v1.4/userguide/scheduling/resource-propagating.md
  versioned_docs/version-v1.5/userguide/scheduling/resource-propagating.md
  versioned_docs/version-v1.6/userguide/scheduling/resource-propagating.md
  versioned_docs/version-v1.7/userguide/scheduling/resource-propagating.md
  versioned_docs/version-v1.8/userguide/scheduling/resource-propagating.md
Labels: kind/documentation, approved, lgtm, size/L

#566 add case study for unionbigdata in English
  docs/casestudies/static/unionbigdata_01.png
  docs/casestudies/static/unionbigdata_02.png
  docs/casestudies/unionbigdata.md
  i18n/zh/docusaurus-plugin-content-docs/current/casestudies/static/unionbigdata_01.png
  i18n/zh/docusaurus-plugin-content-docs/current/casestudies/static/unionbigdata_02.png
Labels: kind/documentation, approved, lgtm, size/M

#568 Update karmadactl command document
  docs/reference/components/karmada-agent.md
  docs/reference/components/karmada-aggregated-apiserver.md
  docs/reference/components/karmada-controller-manager.md
  docs/reference/components/karmada-metrics-adapter.md
  docs/reference/components/karmada-scheduler-estimator.md
  docs/reference/components/karmada-scheduler.md
  docs/reference/components/karmada-search.md
  docs/reference/karmadactl/karmadactl-commands/karmadactl_index.md
  docs/reference/karmadactl/karmadactl-commands/karmadactl_init.md
  docs/reference/karmadactl/karmadactl-commands/karmadactl_interpret.md
  i18n/zh/docusaurus-plugin-content-docs/current/reference/components/karmada-agent.md
  i18n/zh/docusaurus-plugin-content-docs/current/reference/components/karmada-aggregated-apiserver.md
  i18n/zh/docusaurus-plugin-content-docs/current/reference/components/karmada-controller-manager.md
  i18n/zh/docusaurus-plugin-content-docs/current/reference/components/karmada-metrics-adapter.md
  i18n/zh/docusaurus-plugin-content-docs/current/reference/components/karmada-scheduler-estimator.md
  i18n/zh/docusaurus-plugin-content-docs/current/reference/components/karmada-scheduler.md
  i18n/zh/docusaurus-plugin-content-docs/current/reference/components/karmada-search.md
  i18n/zh/docusaurus-plugin-content-docs/current/reference/karmadactl/karmadactl-commands/karmadactl_index.md
  i18n/zh/docusaurus-plugin-content-docs/current/reference/karmadactl/karmadactl-commands/karmadactl_init.md
  i18n/zh/docusaurus-plugin-content-docs/current/reference/karmadactl/karmadactl-commands/karmadactl_interpret.md
Labels: kind/documentation, approved, lgtm, size/L
