Repository karmada-io/website, pull requests merged in 2024-05, with the labels that each got.

#600 doc: fix nit bugs in chinese document
  i18n/zh/docusaurus-plugin-content-docs/current/contributor/contribute-docs.md
  i18n/zh/docusaurus-plugin-content-docs/current/tutorials/crd-application.md
Labels: size/XS, kind/documentation, approved, lgtm

#603 doc: translate zh/tutorials/autoscaling-with-custom-metrics
  docs/tutorials/autoscaling-with-custom-metrics.md
  i18n/zh/docusaurus-plugin-content-docs/current/tutorials/autoscaling-with-custom-metrics.md
  i18n/zh/docusaurus-plugin-content-docs/current/tutorials/autoscaling-with-resource-metrics.md
Labels: kind/documentation, approved, lgtm, size/L

#604 Change the targetPort in the example to 80
  docs/tutorials/access-service-across-clusters.md
  i18n/zh/docusaurus-plugin-content-docs/current/tutorials/access-service-across-clusters.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.9/tutorials/access-service-across-clusters.md
  versioned_docs/version-v1.9/tutorials/access-service-across-clusters.md
Labels: size/XS, kind/documentation, approved, lgtm

#605 doc: format command line prompts
  docs/administrator/backup/working-with-velero.md
  docs/administrator/migration/migration-from-kubefed.md
  docs/developers/customize-karmada-scheduler.md
  docs/developers/document-releasing.md
  docs/developers/performance-test-setup-for-karmada.md
  docs/developers/profiling-karmada.md
  docs/get-started/nginx-example.md
  docs/installation/install-binary.md
  docs/installation/installation.md
  docs/tutorials/access-service-across-clusters.md
  docs/tutorials/autoscaling-with-custom-metrics.md
  docs/tutorials/autoscaling-with-resource-metrics.md
  docs/tutorials/resource-migration.md
  docs/userguide/cicd/working-with-argocd.md
  docs/userguide/clustermanager/cluster-registration.md
  docs/userguide/failover/application-failover.md
  docs/userguide/globalview/proxy-global-resource.md
  docs/userguide/scheduling/descheduler.md
  docs/userguide/scheduling/resource-propagating.md
  docs/userguide/scheduling/scheduler-estimator.md
  docs/userguide/security-governance/working-with-gatekeeper.md
  docs/userguide/service/multi-cluster-service.md
  docs/userguide/service/working-with-eriecanal.md
  docs/userguide/service/working-with-istio-on-flat-network.md
  i18n/zh/docusaurus-plugin-content-docs/current/administrator/backup/working-with-velero.md
  i18n/zh/docusaurus-plugin-content-docs/current/administrator/migration/migration-from-kubefed.md
  i18n/zh/docusaurus-plugin-content-docs/current/developers/customize-karmada-scheduler.md
  i18n/zh/docusaurus-plugin-content-docs/current/developers/document-releasing.md
  i18n/zh/docusaurus-plugin-content-docs/current/developers/performance-test-setup-for-karmada.md
  i18n/zh/docusaurus-plugin-content-docs/current/developers/profiling-karmada.md
  i18n/zh/docusaurus-plugin-content-docs/current/get-started/nginx-example.md
  i18n/zh/docusaurus-plugin-content-docs/current/installation/install-binary.md
  i18n/zh/docusaurus-plugin-content-docs/current/installation/installation.md
  i18n/zh/docusaurus-plugin-content-docs/current/tutorials/access-service-across-clusters.md
  i18n/zh/docusaurus-plugin-content-docs/current/tutorials/autoscaling-with-custom-metrics.md
  i18n/zh/docusaurus-plugin-content-docs/current/tutorials/autoscaling-with-resource-metrics.md
  i18n/zh/docusaurus-plugin-content-docs/current/tutorials/resource-migration.md
  i18n/zh/docusaurus-plugin-content-docs/current/userguide/cicd/working-with-argocd.md
  i18n/zh/docusaurus-plugin-content-docs/current/userguide/clustermanager/cluster-registration.md
  i18n/zh/docusaurus-plugin-content-docs/current/userguide/failover/application-failover.md
  i18n/zh/docusaurus-plugin-content-docs/current/userguide/globalview/proxy-global-resource.md
  i18n/zh/docusaurus-plugin-content-docs/current/userguide/scheduling/descheduler.md
  i18n/zh/docusaurus-plugin-content-docs/current/userguide/scheduling/resource-propagating.md
  i18n/zh/docusaurus-plugin-content-docs/current/userguide/scheduling/scheduler-estimator.md
  i18n/zh/docusaurus-plugin-content-docs/current/userguide/security-governance/working-with-gatekeeper.md
  i18n/zh/docusaurus-plugin-content-docs/current/userguide/service/multi-cluster-service.md
  i18n/zh/docusaurus-plugin-content-docs/current/userguide/service/working-with-eriecanal.md
  i18n/zh/docusaurus-plugin-content-docs/current/userguide/service/working-with-istio-on-flat-network.md
Labels: kind/documentation, approved, lgtm, size/L

#607 doc: translate zh/tutorials/access-service-across-clusters
  docs/tutorials/access-service-across-clusters.md
  i18n/zh/docusaurus-plugin-content-docs/current/tutorials/access-service-across-clusters.md
  i18n/zh/docusaurus-plugin-content-docs/current/tutorials/autoscaling-federatedhpa-with-cronfederatedhpa.md
  i18n/zh/docusaurus-plugin-content-docs/current/tutorials/autoscaling-with-custom-metrics.md
  i18n/zh/docusaurus-plugin-content-docs/current/tutorials/autoscaling-with-resource-metrics.md
  i18n/zh/docusaurus-plugin-content-docs/current/tutorials/autoscaling-workload-with-cronfederatedhpa.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.7/tutorials/autoscaling-federatedhpa-with-cronfederatedhpa.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.7/tutorials/autoscaling-workload-with-cronfederatedhpa.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.8/tutorials/autoscaling-federatedhpa-with-cronfederatedhpa.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.8/tutorials/autoscaling-workload-with-cronfederatedhpa.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.9/tutorials/autoscaling-federatedhpa-with-cronfederatedhpa.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.9/tutorials/autoscaling-workload-with-cronfederatedhpa.md
Labels: kind/documentation, approved, lgtm, size/L

#609 doc: translate zh/installation/ha-installation
  docs/installation/ha-installation.md
  i18n/zh/docusaurus-plugin-content-docs/current/installation/ha-installation.md
  i18n/zh/docusaurus-plugin-content-docs/current/resources/general/karmada-external-etcd.png
  i18n/zh/docusaurus-plugin-content-docs/current/resources/general/karmada-stacked-etcd.png
Labels: kind/documentation, approved, lgtm, size/M

#611 update release.md
  docs/developers/releasing.md
  docs/resources/developers/release-compare.png
  i18n/zh/docusaurus-plugin-content-docs/current/developers/releasing.md
  i18n/zh/docusaurus-plugin-content-docs/current/resources/developers/release-compare.png
Labels: kind/documentation, approved, lgtm, size/S

#612 add tutorial for workload-rebalancer
  docs/tutorials/workload-rebalancer.md
  sidebars.js
Labels: kind/documentation, approved, lgtm, size/L

#608 add userguide for workload-rebalancer
  docs/userguide/scheduling/workload-rebalancer.md
  sidebars.js
Labels: kind/feature, kind/documentation, approved, lgtm, size/L

#621 update dependencies
  package-lock.json
  package.json
Labels: approved, lgtm, size/L

#615 doc: translate zh/installation/ha-installation-with-cli
  i18n/zh/docusaurus-plugin-content-docs/current/installation/ha-installation-with-cli.md
Labels: kind/documentation, approved, lgtm, size/M

#618 Update iQIYI url in adopters
  src/pages/adopters.md
Labels: size/XS, kind/documentation, approved, lgtm

#623 Update iQIYI url in adopters(zh)
  i18n/zh/docusaurus-plugin-content-pages/adopters.md
Labels: size/XS, kind/documentation, approved, lgtm

#622 upgrade from v1.9 to v1.10
  docs/administrator/upgrading/README.md
  docs/administrator/upgrading/v1.9-v1.10.md
  i18n/zh/docusaurus-plugin-content-docs/current/administrator/upgrading/README.md
  i18n/zh/docusaurus-plugin-content-docs/current/administrator/upgrading/v1.9-v1.10.md
  sidebars.js
Labels: kind/documentation, approved, lgtm, size/M

#626 update dependencies
  package-lock.json
  package.json
Labels: approved, lgtm, size/L

#627 add zh tutorial for workload-rebalancer
  i18n/zh/docusaurus-plugin-content-docs/current/tutorials/workload-rebalancer.md
Labels: kind/documentation, approved, lgtm, size/L

#628 add zh userguide for workload-rebalancer
  i18n/zh/docusaurus-plugin-content-docs/current/userguide/scheduling/workload-rebalancer.md
Labels: kind/documentation, approved, lgtm, size/L
