Repository karmada-io/website, pull requests merged in 2024-11, with the labels that each got.

#727 update dependencies
  package-lock.json
  package.json
Labels: approved, lgtm, size/L

#732 update dependencies
  package-lock.json
  package.json
Labels: approved, lgtm, size/L

#731 Update workload-rebalancer.md
  docs/userguide/scheduling/workload-rebalancer.md
Labels: kind/documentation, approved, lgtm, size/M

#734 Update autoscaling-with-resource-metrics.md
  docs/tutorials/autoscaling-with-resource-metrics.md
Labels: kind/documentation, approved, lgtm, size/M

#735 Update workload-rebalancer.md
  docs/tutorials/workload-rebalancer.md
Labels: kind/documentation, approved, lgtm, size/M

#738 update dependencies
  package-lock.json
  package.json
Labels: approved, lgtm, size/L

#736 Update cluster-resources.md
  docs/userguide/scheduling/cluster-resources.md
Labels: kind/documentation, approved, lgtm, size/S

#740 update dependencies
  package-lock.json
  package.json
Labels: approved, lgtm, size/L

#742 update dependencies
  package-lock.json
  package.json
Labels: approved, lgtm, size/L

#744 update configure-controller.md
  docs/administrator/configuration/configure-controllers.md
  i18n/zh/docusaurus-plugin-content-docs/current/administrator/configuration/configure-controllers.md
Labels: kind/documentation, approved, lgtm, size/S

#745 [zh] Sync core-concepts/components.md
  i18n/zh/docusaurus-plugin-content-docs/current/core-concepts/components.md
Labels: kind/documentation, approved, lgtm, size/S

#746 add Karmada API Document for v1.12
  docs/reference/karmada-api/cluster-resources/cluster-v1alpha1.md
  docs/reference/karmada-api/common-parameter/common-parameters.md
  docs/reference/karmada-api/policy-resources/cluster-override-policy-v1alpha1.md
  docs/reference/karmada-api/policy-resources/cluster-propagation-policy-v1alpha1.md
  docs/reference/karmada-api/policy-resources/override-policy-v1alpha1.md
  docs/reference/karmada-api/policy-resources/propagation-policy-v1alpha1.md
  docs/reference/karmada-api/search-resources/resource-registry-v1alpha1.md
  docs/reference/karmada-api/work-resources/resource-binding-v1alpha2.md
  docs/reference/karmada-api/work-resources/work-v1alpha1.md
Labels: kind/documentation, approved, lgtm, size/L

#749 Add doc for stateful application failover
  docs/userguide/failover/application-failover.md
  i18n/zh/docusaurus-plugin-content-docs/current/userguide/failover/application-failover.md
Labels: kind/feature, approved, lgtm, size/M

#728 update components-permission docs
  docs/administrator/security/component-permission.md
  docs/administrator/security/rbac-permissions-for-karmada-components.md
  i18n/zh/docusaurus-plugin-content-docs/current/administrator/security/component-permission.md
  i18n/zh/docusaurus-plugin-content-docs/current/administrator/security/rbac-permissions-for-karmada-components.md
  sidebars.js
Labels: kind/feature, approved, lgtm, size/L

#748 upgrade from v1.11 to v1.12
  docs/administrator/upgrading/README.md
  docs/administrator/upgrading/v1.11-v1.12.md
  i18n/zh/docusaurus-plugin-content-docs/current/administrator/upgrading/README.md
  i18n/zh/docusaurus-plugin-content-docs/current/administrator/upgrading/v1.11-v1.12.md
  sidebars.js
Labels: kind/documentation, approved, lgtm, size/M

#751 Set Failover FeatureGate by default
  docs/userguide/failover/application-failover.md
  docs/userguide/failover/failover-overview.md
  i18n/zh/docusaurus-plugin-content-docs/current/userguide/failover/application-failover.md
  i18n/zh/docusaurus-plugin-content-docs/current/userguide/failover/failover-overview.md
Labels: kind/feature, approved, lgtm, size/S

#750 add reference doc for failover
  docs/reference/components/karmada-agent.md
  docs/reference/components/karmada-aggregated-apiserver.md
  docs/reference/components/karmada-controller-manager.md
  docs/reference/components/karmada-scheduler-estimator.md
  docs/reference/components/karmada-scheduler.md
  docs/reference/components/karmada-search.md
  i18n/zh/docusaurus-plugin-content-docs/current/reference/components/karmada-agent.md
  i18n/zh/docusaurus-plugin-content-docs/current/reference/components/karmada-aggregated-apiserver.md
  i18n/zh/docusaurus-plugin-content-docs/current/reference/components/karmada-controller-manager.md
  i18n/zh/docusaurus-plugin-content-docs/current/reference/components/karmada-scheduler-estimator.md
  i18n/zh/docusaurus-plugin-content-docs/current/reference/components/karmada-scheduler.md
  i18n/zh/docusaurus-plugin-content-docs/current/reference/components/karmada-search.md
Labels: kind/documentation, approved, lgtm, size/L
