Repository karmada-io/website, pull requests merged in 2024-12, with the labels that each got.

#753 improve releasing doc
  docs/developers/document-releasing.md
  i18n/zh/docusaurus-plugin-content-docs/current/developers/document-releasing.md
Labels: kind/documentation, approved, lgtm, size/S

#754 add release cycle
  docs/releases.md
  docs/resources/releases/release-cycle.drawio
  docs/resources/releases/release-cycle.png
  docs/resources/releases/release-life-cycle.drawio
  docs/resources/releases/release-life-cycle.png
  docs/resources/releases/release-time-lines.drawio
  docs/resources/releases/release-time-lines.png
  i18n/zh/docusaurus-plugin-content-docs/current/releases.md
  i18n/zh/docusaurus-plugin-content-docs/current/resources/releases/release-cycle.drawio
  i18n/zh/docusaurus-plugin-content-docs/current/resources/releases/release-cycle.png
  i18n/zh/docusaurus-plugin-content-docs/current/resources/releases/release-life-cycle.drawio
  i18n/zh/docusaurus-plugin-content-docs/current/resources/releases/release-life-cycle.png
  i18n/zh/docusaurus-plugin-content-docs/current/resources/releases/release-time-lines.drawio
  i18n/zh/docusaurus-plugin-content-docs/current/resources/releases/release-time-lines.png
Labels: kind/documentation, approved, lgtm, size/XL

#756 update dependencies
  package-lock.json
  package.json
Labels: approved, lgtm, size/L

#758 update dependencies
  package-lock.json
  package.json
Labels: approved, lgtm, size/L

#762 update semi-ui
  package-lock.json
  package.json
Labels: approved, lgtm, size/L

#759 remove beta apiversion
  docs/userguide/cicd/working-with-flux.md
  i18n/zh/docusaurus-plugin-content-docs/current/userguide/cicd/working-with-flux.md
Labels: kind/bug, approved, lgtm, size/L

#763 adds karmadactl flags for proper display
  docs/tutorials/autoscaling-with-custom-metrics.md
  docs/tutorials/autoscaling-with-resource-metrics.md
Labels: kind/documentation, approved, lgtm, size/M

#764 zh: adds karmadactl flags for proper display
  i18n/zh/docusaurus-plugin-content-docs/current/tutorials/autoscaling-with-custom-metrics.md
  i18n/zh/docusaurus-plugin-content-docs/current/tutorials/autoscaling-with-resource-metrics.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.11/tutorials/autoscaling-with-custom-metrics.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.11/tutorials/autoscaling-with-resource-metrics.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.12/tutorials/autoscaling-with-custom-metrics.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.12/tutorials/autoscaling-with-resource-metrics.md
  versioned_docs/version-v1.11/tutorials/autoscaling-with-custom-metrics.md
  versioned_docs/version-v1.11/tutorials/autoscaling-with-resource-metrics.md
  versioned_docs/version-v1.12/tutorials/autoscaling-with-custom-metrics.md
  versioned_docs/version-v1.12/tutorials/autoscaling-with-resource-metrics.md
Labels: kind/documentation, approved, lgtm, size/L

#766 update semi-ui
  package-lock.json
  package.json
Labels: approved, lgtm, size/L

#770 update semi-ui
  package-lock.json
  package.json
Labels: approved, lgtm, size/L

#773 fixing typo in install-binary page
  docs/installation/install-binary.md
  versioned_docs/version-v1.10/installation/install-binary.md
  versioned_docs/version-v1.11/installation/install-binary.md
  versioned_docs/version-v1.12/installation/install-binary.md
  versioned_docs/version-v1.4/installation/install-binary.md
  versioned_docs/version-v1.5/installation/install-binary.md
  versioned_docs/version-v1.6/installation/install-binary.md
  versioned_docs/version-v1.7/installation/install-binary.md
  versioned_docs/version-v1.8/installation/install-binary.md
  versioned_docs/version-v1.9/installation/install-binary.md
Labels: approved, lgtm, size/S

#774 Add adopter for HelloGroup(NASDAQ: MOMO)
  i18n/zh/docusaurus-plugin-content-pages/adopters.md
  src/pages/adopters.md
Labels: size/XS, kind/documentation, approved, lgtm

#775 add bilibili to karmada adopters
  i18n/zh/docusaurus-plugin-content-pages/adopters.md
  src/pages/adopters.md
Labels: size/XS, kind/documentation, approved, lgtm
