Repository karmada-io/website, pull requests merged in 2024-08, with the labels that each got.

#666 add sidebar for v1.10 missed workload rebalancer doc
  i18n/zh/docusaurus-plugin-content-docs/version-v1.10/tutorials/workload-rebalancer.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.10/userguide/scheduling/workload-rebalancer.md
  versioned_sidebars/version-v1.10-sidebars.json
Labels: kind/documentation, approved, lgtm, size/S

#668 docs: cluster-level resource propagation pause and resume capabilities
  docs/reference/instrumentation/event.md
  docs/resources/general/execution-controller-process.drawio
  docs/resources/general/execution-controller-process.png
  docs/userguide/scheduling/resource-propagating.md
Labels: kind/feature, approved, lgtm, size/M

#670 update dependencies
  package-lock.json
  package.json
Labels: approved, lgtm, size/L

#671 translate: cluster-level resource propagation pause and resume capabilities
  docs/userguide/scheduling/resource-propagating.md
  i18n/zh/docusaurus-plugin-content-docs/current/reference/instrumentation/event.md
  i18n/zh/docusaurus-plugin-content-docs/current/resources/general/execution-controller-process.drawio
  i18n/zh/docusaurus-plugin-content-docs/current/resources/general/execution-controller-process.png
  i18n/zh/docusaurus-plugin-content-docs/current/userguide/scheduling/resource-propagating.md
Labels: kind/documentation, approved, lgtm, size/M

#655 add slsa verifier
  docs/administrator/security/verify-artifacts.md
  typos.toml
Labels: kind/documentation, approved, lgtm, size/M

#672 fix nits in application failover doc
  docs/userguide/failover/application-failover.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.10/userguide/failover/application-failover.md
Labels: size/XS, kind/documentation, approved, lgtm

#673 fix: typo in promote-legacy-workload.md
  docs/administrator/migration/promote-legacy-workload.md
  versioned_docs/version-v1.10/administrator/migration/promote-legacy-workload.md
  versioned_docs/version-v1.3/administrator/migration/promote-legacy-workload.md
  versioned_docs/version-v1.4/administrator/migration/promote-legacy-workload.md
  versioned_docs/version-v1.5/administrator/migration/promote-legacy-workload.md
  versioned_docs/version-v1.6/administrator/migration/promote-legacy-workload.md
  versioned_docs/version-v1.7/administrator/migration/promote-legacy-workload.md
  versioned_docs/version-v1.8/administrator/migration/promote-legacy-workload.md
  versioned_docs/version-v1.9/administrator/migration/promote-legacy-workload.md
Labels: kind/bug, approved, lgtm, size/M

#675 update dependencies
  package-lock.json
  package.json
Labels: approved, lgtm, size/L
