Repository karmada-io/website, pull requests merged in 2024-09, with the labels that each got.

#679 add Karmada API Document for v1.11
  docs/reference/karmada-api/common-definitions/delete-options.md
  docs/reference/karmada-api/common-definitions/label-selector.md
  docs/reference/karmada-api/common-definitions/node-selector-requirement.md
  docs/reference/karmada-api/common-definitions/object-meta.md
  docs/reference/karmada-api/common-definitions/status.md
  docs/reference/karmada-api/networking-resources/multi-cluster-ingress-v1alpha1.md
  docs/reference/karmada-api/networking-resources/multi-cluster-service-v1alpha1.md
  docs/reference/karmada-api/policy-resources/cluster-override-policy-v1alpha1.md
  docs/reference/karmada-api/policy-resources/cluster-propagation-policy-v1alpha1.md
  docs/reference/karmada-api/policy-resources/override-policy-v1alpha1.md
  docs/reference/karmada-api/policy-resources/propagation-policy-v1alpha1.md
  docs/reference/karmada-api/search-resources/resource-registry-v1alpha1.md
  docs/reference/karmada-api/work-resources/resource-binding-v1alpha2.md
  docs/reference/karmada-api/work-resources/work-v1alpha1.md
Labels: kind/documentation, approved, lgtm, size/L

#678 upgrade from v1.10 to v1.11
  docs/administrator/upgrading/README.md
  docs/administrator/upgrading/v1.10-v1.11.md
  i18n/zh/docusaurus-plugin-content-docs/current/administrator/upgrading/README.md
  i18n/zh/docusaurus-plugin-content-docs/current/administrator/upgrading/v1.10-v1.11.md
  sidebars.js
Labels: kind/documentation, approved, lgtm, size/M

#681 Update wrong yaml writing in Suspend and resume of resource propagation
  docs/userguide/scheduling/resource-propagating.md
  i18n/zh/docusaurus-plugin-content-docs/current/userguide/scheduling/resource-propagating.md
Labels: kind/bug, size/XS, kind/documentation, approved, lgtm

#683 update dependencies
  package-lock.json
  package.json
Labels: approved, lgtm, size/L

#680 Add Karmada x PipeCD guideline
  docs/resources/userguide/cicd/pipecd/pipecd-add-app-done.png
  docs/resources/userguide/cicd/pipecd/pipecd-add-new-app.png
  docs/resources/userguide/cicd/pipecd/pipecd-app-detail-page.png
  docs/resources/userguide/cicd/pipecd/pipecd-app-first-deploy.png
  docs/resources/userguide/cicd/pipecd/pipecd-app-first-sync.png
  docs/resources/userguide/cicd/pipecd/pipecd-new-app-info.png
  docs/resources/userguide/cicd/pipecd/pipecd-ready-page.png
  docs/resources/userguide/cicd/pipecd/piped-ready-status.png
  docs/userguide/cicd/working-with-pipecd.md
  sidebars.js
Labels: kind/documentation, approved, lgtm, size/L

#684 update dependencies
  package-lock.json
  package.json
Labels: approved, lgtm, size/L

#685 Fix words mismatched with images
  docs/userguide/cicd/working-with-pipecd.md
Labels: kind/bug, size/XS, approved, lgtm

#686 Add WPS to adopters
  src/data/supporters.js
  src/pages/adopters.md
  static/img/supporters/wps.png
Labels: size/XS, approved, lgtm

#689 format cleanup for adopter doc
  src/pages/adopters.md
Labels: kind/cleanup, approved, lgtm, size/M

#688 Add WPS to adopters (zh)
  i18n/zh/docusaurus-plugin-content-pages/adopters.md
Labels: kind/documentation, approved, lgtm, size/M

#687 Add v1.11 releasing blog
  blog/2024-09-13-karmada-v1.11/img/contributors.png
  blog/2024-09-13-karmada-v1.11/img/rollout-00.png
  blog/2024-09-13-karmada-v1.11/img/rollout-01.png
  blog/2024-09-13-karmada-v1.11/img/rollout-02.png
  blog/2024-09-13-karmada-v1.11/img/rollout-03.png
  blog/2024-09-13-karmada-v1.11/karmada-v1.11.md
  i18n/zh/docusaurus-plugin-content-blog/2024-09-13-karmada-v1.11/img/contributors.png
  i18n/zh/docusaurus-plugin-content-blog/2024-09-13-karmada-v1.11/img/rollout-00.png
  i18n/zh/docusaurus-plugin-content-blog/2024-09-13-karmada-v1.11/img/rollout-01.png
  i18n/zh/docusaurus-plugin-content-blog/2024-09-13-karmada-v1.11/img/rollout-02.png
  i18n/zh/docusaurus-plugin-content-blog/2024-09-13-karmada-v1.11/img/rollout-03.png
  i18n/zh/docusaurus-plugin-content-blog/2024-09-13-karmada-v1.11/karmada-v1.11.md
Labels: kind/documentation, approved, lgtm, size/L

#692 update dependencies
  package-lock.json
  package.json
Labels: approved, lgtm, size/L
