Repository karmada-io/website, pull requests merged in 2024-04, with the labels that each got.

#588 Add ClusterEviction plugin
  docs/developers/customize-karmada-scheduler.md
  i18n/zh/docusaurus-plugin-content-docs/current/developers/customize-karmada-scheduler.md
Labels: kind/documentation, approved, lgtm, size/M

#589 nominate windsonsea to the global reviewers
  OWNERS
Labels: size/XS, kind/documentation, approved, lgtm

#578 Add checklist for adding new API
  docs/developers/add-new-api.md
  i18n/zh/docusaurus-plugin-content-docs/current/developers/add-new-api.md
  sidebars.js
Labels: kind/documentation, approved, lgtm, size/L

#590 Update `istio x create-remote-secret` examples to `istio create-remote-secret`
  docs/userguide/service/working-with-istio-on-flat-network.md
  docs/userguide/service/working-with-istio-on-non-flat-network.md
  i18n/zh/docusaurus-plugin-content-docs/current/userguide/service/working-with-istio-on-flat-network.md
  i18n/zh/docusaurus-plugin-content-docs/current/userguide/service/working-with-istio-on-non-flat-network.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.3/userguide/service/working-with-istio-on-flat-network.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.3/userguide/service/working-with-istio-on-non-flat-network.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.4/userguide/service/working-with-istio-on-flat-network.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.4/userguide/service/working-with-istio-on-non-flat-network.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.5/userguide/service/working-with-istio-on-flat-network.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.5/userguide/service/working-with-istio-on-non-flat-network.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.6/userguide/service/working-with-istio-on-flat-network.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.6/userguide/service/working-with-istio-on-non-flat-network.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.7/userguide/service/working-with-istio-on-flat-network.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.7/userguide/service/working-with-istio-on-non-flat-network.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.8/userguide/service/working-with-istio-on-flat-network.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.8/userguide/service/working-with-istio-on-non-flat-network.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.9/userguide/service/working-with-istio-on-flat-network.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.9/userguide/service/working-with-istio-on-non-flat-network.md
  versioned_docs/version-v1.3/userguide/service/working-with-istio-on-flat-network.md
  versioned_docs/version-v1.3/userguide/service/working-with-istio-on-non-flat-network.md
  versioned_docs/version-v1.4/userguide/service/working-with-istio-on-flat-network.md
  versioned_docs/version-v1.4/userguide/service/working-with-istio-on-non-flat-network.md
  versioned_docs/version-v1.5/userguide/service/working-with-istio-on-flat-network.md
  versioned_docs/version-v1.5/userguide/service/working-with-istio-on-non-flat-network.md
  versioned_docs/version-v1.6/userguide/service/working-with-istio-on-flat-network.md
  versioned_docs/version-v1.6/userguide/service/working-with-istio-on-non-flat-network.md
  versioned_docs/version-v1.7/userguide/service/working-with-istio-on-flat-network.md
  versioned_docs/version-v1.7/userguide/service/working-with-istio-on-non-flat-network.md
  versioned_docs/version-v1.8/userguide/service/working-with-istio-on-flat-network.md
  versioned_docs/version-v1.8/userguide/service/working-with-istio-on-non-flat-network.md
  versioned_docs/version-v1.9/userguide/service/working-with-istio-on-flat-network.md
  versioned_docs/version-v1.9/userguide/service/working-with-istio-on-non-flat-network.md
Labels: kind/documentation, approved, lgtm, size/M

#594 Fix typos on docs
  docs/core-concepts/concepts.md
  docs/key-features/features.md
  versioned_docs/version-v1.3/faq/faq.md
Labels: size/XS, kind/documentation, approved, lgtm

#597 update dependencies
  package-lock.json
  package.json
Labels: approved, lgtm, size/L

#595 Docs typo fixes
  docs/faq/faq.md
  docs/key-features/features.md
  docs/userguide/clustermanager/cluster-registration.md
Labels: kind/documentation, approved, lgtm, size/M
