Repository karmada-io/website, pull requests merged in 2024-06, with the labels that each got.

#629 add mutate configuration description for upgrading v1.9-v1.10
  docs/administrator/upgrading/v1.9-v1.10.md
  i18n/zh/docusaurus-plugin-content-docs/current/administrator/upgrading/v1.9-v1.10.md
Labels: kind/documentation, approved, lgtm, size/L

#630 add deprecated label for upgrading v1.9-v1.10
  docs/administrator/upgrading/v1.9-v1.10.md
  i18n/zh/docusaurus-plugin-content-docs/current/administrator/upgrading/v1.9-v1.10.md
Labels: size/XS, kind/documentation, approved, lgtm

#632 update API reference docs of release-1.10
  docs/reference/karmada-api/app-resources/workload-rebalancer-v1alpha1.md
  docs/reference/karmada-api/common-parameter/common-parameters.md
  docs/reference/karmada-api/config-resources/resource-interpreter-customization-v1alpha1.md
  docs/reference/karmada-api/networking-resources/multi-cluster-service-v1alpha1.md
  docs/reference/karmada-api/work-resources/resource-binding-v1alpha2.md
  i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/app-resources/workload-rebalancer-v1alpha1.md
  i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/common-parameter/common-parameters.md
  i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/config-resources/resource-interpreter-customization-v1alpha1.md
  i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/networking-resources/multi-cluster-service-v1alpha1.md
  i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/remedy-resources/remedy-v1alpha1.md
  i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/work-resources/resource-binding-v1alpha2.md
  sidebars.js
Labels: size/XXL, kind/documentation, approved, lgtm

#636 update dependencies
  package-lock.json
  package.json
Labels: approved, lgtm, size/L

#638 translate remedy api
  i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/remedy-resources/remedy-v1alpha1.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.10/reference/karmada-api/remedy-resources/remedy-v1alpha1.md
Labels: kind/documentation, approved, lgtm, size/XL

#640 Add KubeCon talks of trip
  i18n/zh/docusaurus-plugin-content-pages/adopters.md
  src/pages/adopters.md
Labels: kind/documentation, approved, lgtm, size/L

#639 translate WorkloadRebalancer api
  i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/app-resources/workload-rebalancer-v1alpha1.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.10/reference/karmada-api/app-resources/workload-rebalancer-v1alpha1.md
  versioned_sidebars/version-v1.10-sidebars.json
Labels: approved, lgtm, size/XL

#641 adopter onboarding for Li Auto
  i18n/zh/docusaurus-plugin-content-pages/adopters.md
  src/pages/adopters.md
Labels: size/XS, kind/documentation, approved, lgtm

#643 update dependencies
  package-lock.json
  package.json
Labels: approved, lgtm, size/L

#645 fix wrong url in zh docs components.md
  i18n/zh/docusaurus-plugin-content-docs/current/core-concepts/components.md
Labels: size/XS, kind/documentation, approved, lgtm

#647 update dependencies
  package-lock.json
  package.json
Labels: approved, lgtm, size/L

#648 add tongccheng travel adopter
  i18n/zh/docusaurus-plugin-content-pages/adopters.md
  src/pages/adopters.md
Labels: size/XS, kind/documentation, approved, lgtm

#649 Adjust adopters sorted alphabetically by the first letter of their English names
  i18n/zh/docusaurus-plugin-content-pages/adopters.md
  src/pages/adopters.md
Labels: kind/cleanup, approved, lgtm, size/M
