Repository karmada-io/website, pull requests merged in 2024-07, with the labels that each got.

#650 clean up namespace management and add manual option
  docs/userguide/bestpractices/namespace-management.md
Labels: kind/documentation, approved, lgtm, size/M

#644 doc: translate zh/userguide/clustermanager/cluster-registration
  i18n/zh/docusaurus-plugin-content-docs/current/userguide/clustermanager/cluster-registration.md
Labels: kind/documentation, approved, lgtm, size/L

#652 Add sbom to release assets
  docs/administrator/security/verify-artifacts.md
  docs/releases.md
  i18n/zh/docusaurus-plugin-content-docs/current/administrator/security/verify-artifacts.md
Labels: kind/documentation, approved, lgtm, size/L

#658 docs: add a hint in the resource-propagation
  docs/userguide/scheduling/resource-propagating.md
Labels: size/XS, kind/documentation, approved, lgtm

#661 update dependencies
  package-lock.json
  package.json
Labels: approved, lgtm, size/L

#663 update dependencies
  package-lock.json
  package.json
Labels: approved, lgtm, size/L

#667 update dependencies
  package-lock.json
  package.json
Labels: approved, lgtm, size/L

#665 add zh metrics doc for recreate/update_resource_to_cluster
  i18n/zh/docusaurus-plugin-content-docs/current/reference/instrumentation/metrics.md
Labels: size/XS, kind/documentation, approved, lgtm
