Repository karmada-io/website, pull requests merged in 2024-10, with the labels that each got.

#701 update dependencies
  package-lock.json
  package.json
Labels: approved, lgtm, size/S

#704 Update customize-karmada-scheduler.md
  docs/developers/customize-karmada-scheduler.md
Labels: size/XS, kind/documentation, approved, lgtm

#705 Add Longbridge to adopters
  i18n/zh/docusaurus-plugin-content-pages/adopters.md
  src/pages/adopters.md
Labels: size/XS, approved, lgtm

#693 docs: fieldoverrider docs
  docs/userguide/scheduling/override-policy.md
  i18n/zh/docusaurus-plugin-content-docs/current/userguide/scheduling/override-policy.md
Labels: kind/documentation, approved, lgtm, size/L

#706 Update file line terminator from CRLF to LF
  docs/administrator/migration/migration-from-kubefed.md
  docs/administrator/security/security-considerations.md
  i18n/zh/docusaurus-plugin-content-docs/current/administrator/security/security-considerations.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.10/administrator/security/security-considerations.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.11/administrator/security/security-considerations.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.9/administrator/security/security-considerations.md
  versioned_docs/version-v1.10/administrator/migration/migration-from-kubefed.md
  versioned_docs/version-v1.10/administrator/security/security-considerations.md
  versioned_docs/version-v1.11/administrator/migration/migration-from-kubefed.md
  versioned_docs/version-v1.11/administrator/security/security-considerations.md
  versioned_docs/version-v1.6/administrator/migration/migration-from-kubefed.md
  versioned_docs/version-v1.7/administrator/migration/migration-from-kubefed.md
  versioned_docs/version-v1.8/administrator/migration/migration-from-kubefed.md
  versioned_docs/version-v1.9/administrator/migration/migration-from-kubefed.md
  versioned_docs/version-v1.9/administrator/security/security-considerations.md
Labels: size/XXL, kind/cleanup, approved, lgtm

#708 update dependencies
  package-lock.json
  package.json
Labels: approved, lgtm, size/L

#710 Update faq.md
  docs/faq/faq.md
Labels: size/XS, kind/documentation, approved, lgtm

#711 Update resource-propagating.md
  docs/userguide/scheduling/resource-propagating.md
Labels: kind/documentation, approved, lgtm, size/M

#712 Update scheduler-estimator.md
  docs/userguide/scheduling/scheduler-estimator.md
Labels: size/XS, kind/documentation, approved, lgtm

#713 Update cluster-resources.md
  docs/userguide/scheduling/cluster-resources.md
Labels: kind/documentation, approved, lgtm, size/M

#716 update dependencies
  package-lock.json
  package.json
Labels: approved, lgtm, size/L

#718 Update propagate-dependencies.md
  docs/userguide/scheduling/propagate-dependencies.md
Labels: size/XS, kind/documentation, approved, lgtm

#717 Update override-policy.md
  docs/userguide/scheduling/override-policy.md
Labels: kind/documentation, approved, lgtm, size/M

#719 Update resource-propagating.md
  docs/userguide/scheduling/resource-propagating.md
Labels: kind/documentation, approved, lgtm, size/S

#722 update dependencies
  package-lock.json
  package.json
Labels: approved, lgtm, size/L

#724 update dependencies
  package-lock.json
  package.json
Labels: approved, lgtm, size/L

#697 add administrator doc in website repo about how to do migration rollback
  docs/administrator/migration/migrate-in-batch.md
  i18n/zh/docusaurus-plugin-content-docs/current/administrator/migration/migrate-in-batch.md
Labels: kind/documentation, approved, lgtm, size/L

#698 add tutorial doc in website repo about how to do migration rollback
  docs/tutorials/resource-migration.md
  i18n/zh/docusaurus-plugin-content-docs/current/tutorials/resource-migration.md
Labels: kind/documentation, approved, lgtm, size/L

#690 add karmadactl init --config & karmadactl config documents
  docs/installation/install-with-cli.md
  docs/installation/installation.md
  docs/reference/karmadactl/karmadactl-commands/karmadactl_annotate.md
  docs/reference/karmadactl/karmadactl-commands/karmadactl_api-resources.md
  docs/reference/karmadactl/karmadactl-commands/karmadactl_api-versions.md
  docs/reference/karmadactl/karmadactl-commands/karmadactl_apply.md
  docs/reference/karmadactl/karmadactl-commands/karmadactl_attach.md
  docs/reference/karmadactl/karmadactl-commands/karmadactl_create.md
  docs/reference/karmadactl/karmadactl-commands/karmadactl_create_clusterrole.md
  docs/reference/karmadactl/karmadactl-commands/karmadactl_create_clusterrolebinding.md
  docs/reference/karmadactl/karmadactl-commands/karmadactl_create_configmap.md
  docs/reference/karmadactl/karmadactl-commands/karmadactl_create_cronjob.md
  docs/reference/karmadactl/karmadactl-commands/karmadactl_create_deployment.md
  docs/reference/karmadactl/karmadactl-commands/karmadactl_create_ingress.md
  docs/reference/karmadactl/karmadactl-commands/karmadactl_create_job.md
  docs/reference/karmadactl/karmadactl-commands/karmadactl_create_namespace.md
  docs/reference/karmadactl/karmadactl-commands/karmadactl_create_poddisruptionbudget.md
  docs/reference/karmadactl/karmadactl-commands/karmadactl_create_priorityclass.md
  docs/reference/karmadactl/karmadactl-commands/karmadactl_create_quota.md
  docs/reference/karmadactl/karmadactl-commands/karmadactl_create_role.md
  docs/reference/karmadactl/karmadactl-commands/karmadactl_create_rolebinding.md
  docs/reference/karmadactl/karmadactl-commands/karmadactl_create_secret.md
  docs/reference/karmadactl/karmadactl-commands/karmadactl_create_secret_docker-registry.md
  docs/reference/karmadactl/karmadactl-commands/karmadactl_create_secret_generic.md
  docs/reference/karmadactl/karmadactl-commands/karmadactl_create_secret_tls.md
  docs/reference/karmadactl/karmadactl-commands/karmadactl_create_service.md
  docs/reference/karmadactl/karmadactl-commands/karmadactl_create_service_clusterip.md
  docs/reference/karmadactl/karmadactl-commands/karmadactl_create_service_externalname.md
  docs/reference/karmadactl/karmadactl-commands/karmadactl_create_service_loadbalancer.md
  docs/reference/karmadactl/karmadactl-commands/karmadactl_create_service_nodeport.md
  docs/reference/karmadactl/karmadactl-commands/karmadactl_create_serviceaccount.md
  docs/reference/karmadactl/karmadactl-commands/karmadactl_create_token.md
  docs/reference/karmadactl/karmadactl-commands/karmadactl_delete.md
  docs/reference/karmadactl/karmadactl-commands/karmadactl_describe.md
  docs/reference/karmadactl/karmadactl-commands/karmadactl_edit.md
  docs/reference/karmadactl/karmadactl-commands/karmadactl_exec.md
  docs/reference/karmadactl/karmadactl-commands/karmadactl_explain.md
  docs/reference/karmadactl/karmadactl-commands/karmadactl_get.md
  docs/reference/karmadactl/karmadactl-commands/karmadactl_init.md
  docs/reference/karmadactl/karmadactl-commands/karmadactl_label.md
  docs/reference/karmadactl/karmadactl-commands/karmadactl_logs.md
  docs/reference/karmadactl/karmadactl-commands/karmadactl_patch.md
  docs/reference/karmadactl/karmadactl-commands/karmadactl_promote.md
  docs/reference/karmadactl/karmadactl-commands/karmadactl_top_node.md
  docs/reference/karmadactl/karmadactl-commands/karmadactl_top_pod.md
  docs/reference/karmadactl/karmadactl-config.v1alpha1.md
  sidebars.js
Labels: kind/feature, approved, lgtm, size/XL

#695 add docs-zh for karmada components-rbac
  i18n/zh/docusaurus-plugin-content-docs/current/administrator/security/rbac-permissions-for-karmada-components.md
Labels: kind/documentation, approved, lgtm, size/M

#696 add docs for karmada components-rbac
  docs/administrator/security/rbac-permissions-for-karmada-components.md
  sidebars.js
Labels: kind/documentation, approved, lgtm, size/M
