Repository karmada-io/website, pull requests merged in 2024-01, with the labels that each got.

#453 Add HA installation with CLI
  docs/installation/ha-installation-with-cli.md
  sidebars.js
Labels: kind/documentation, approved, lgtm, size/M

#531 feature: support Business Partners module
  docusaurus.config.js
  i18n/zh/code.json
  i18n/zh/docusaurus-plugin-content-pages/partners.tsx
  i18n/zh/docusaurus-theme-classic/navbar.json
  package-lock.json
  package.json
  src/data/partnersData.tsx
  src/pages/partners.tsx
  src/pages/styles.module.css
  static/img/supporters/DSK.png
Labels: kind/feature, approved, lgtm, size/XL

#382 preview locally using Docker
  .dockerignore
  Dockerfile
  Makefile
  README.md
  bs-config.js
  package-lock.json
  package.json
  start-watch.sh
Labels: kind/feature, approved, lgtm, size/L

#545 update node version for netlify
  netlify.toml
Labels: kind/feature, size/XS, approved, lgtm

#547 remove redundant content in the Installation Overview chapter
  docs/installation/installation.md
  i18n/zh/docusaurus-plugin-content-docs/current/installation/installation.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.3/installation/installation.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.4/installation/installation.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.5/installation/installation.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.6/installation/installation.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.7/installation/installation.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.8/installation/installation.md
  versioned_docs/version-v1.3/installation/installation.md
  versioned_docs/version-v1.4/installation/installation.md
  versioned_docs/version-v1.5/installation/installation.md
  versioned_docs/version-v1.6/installation/installation.md
  versioned_docs/version-v1.7/installation/installation.md
  versioned_docs/version-v1.8/installation/installation.md
Labels: kind/documentation, approved, lgtm, size/M

#548 doc: add user guide and tutorial doc of mcs
  docs/resources/userguide/service/multiclusterservice/mcs-overview.drawio
  docs/resources/userguide/service/multiclusterservice/mcs-overview.png
  docs/resources/userguide/service/multiclusterservice/mcs-way-of-work.drawio
  docs/resources/userguide/service/multiclusterservice/mcs-way-of-work.png
  docs/tutorials/access-service-across-clusters.md
  docs/userguide/service/multi-cluster-service-with-native-svc-access.mdx
  i18n/zh/docusaurus-plugin-content-docs/current/resources/userguide/service/multiclusterservice/mcs-overview.drawio
  i18n/zh/docusaurus-plugin-content-docs/current/resources/userguide/service/multiclusterservice/mcs-overview.png
  i18n/zh/docusaurus-plugin-content-docs/current/resources/userguide/service/multiclusterservice/mcs-way-of-work.drawio
  i18n/zh/docusaurus-plugin-content-docs/current/resources/userguide/service/multiclusterservice/mcs-way-of-work.png
  i18n/zh/docusaurus-plugin-content-docs/current/tutorials/access-service-across-clusters.md
  i18n/zh/docusaurus-plugin-content-docs/current/userguide/service/multi-cluster-service-with-native-svc-access.mdx
  sidebars.js
Labels: size/XXL, approved, lgtm

#537 Add a case study about BOE for unionbigdata
  docs/casestudies/static/unionbigdata_01.png
  docs/casestudies/static/unionbigdata_02.png
  docs/casestudies/static/unionbigdata_03.png
  docs/casestudies/static/unionbigdata_04.png
  docs/casestudies/static/unionbigdata_05.png
  docs/casestudies/static/unionbigdata_06.png
  docs/casestudies/static/unionbigdata_07.png
  docs/casestudies/unionbigdata.md
  i18n/zh/docusaurus-plugin-content-docs/current/casestudies/static/unionbigdata_01.png
  i18n/zh/docusaurus-plugin-content-docs/current/casestudies/static/unionbigdata_02.png
  i18n/zh/docusaurus-plugin-content-docs/current/casestudies/static/unionbigdata_03.png
  i18n/zh/docusaurus-plugin-content-docs/current/casestudies/static/unionbigdata_04.png
  i18n/zh/docusaurus-plugin-content-docs/current/casestudies/static/unionbigdata_05.png
  i18n/zh/docusaurus-plugin-content-docs/current/casestudies/static/unionbigdata_06.png
  i18n/zh/docusaurus-plugin-content-docs/current/casestudies/static/unionbigdata_07.png
  i18n/zh/docusaurus-plugin-content-docs/current/casestudies/unionbigdata.md
  sidebars.js
Labels: kind/documentation, approved, lgtm, size/L

#549 Rename partner name of unionbigdata
  i18n/zh/code.json
  src/data/partnersData.tsx
  src/pages/adopters.md
  static/img/supporters/unionbigdata.png
Labels: kind/documentation, approved, lgtm, size/S

#550 Make some updation on work-with-submariner doc
  docs/userguide/network/working-with-submariner.md
  i18n/zh/docusaurus-plugin-content-docs/current/userguide/network/working-with-submariner.md
Labels: kind/cleanup, kind/documentation, approved, lgtm, size/S

#553 fix typos error of documents
  blog/2022-10-26-test-report/index.md
  docs/reference/karmada-api/common-definitions/quantity.md
  docs/tutorials/access-service-across-clusters.md
  i18n/zh/docusaurus-plugin-content-blog/2022-10-26-test-report/index.md
  i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/common-definitions/quantity.md
  i18n/zh/docusaurus-plugin-content-docs/current/tutorials/access-service-across-clusters.md
  i18n/zh/docusaurus-plugin-content-docs/current/tutorials/autoscaling-with-resource-metrics.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.8/reference/karmada-api/common-definitions/quantity.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.8/tutorials/autoscaling-with-resource-metrics.md
  versioned_docs/version-v1.8/reference/karmada-api/common-definitions/quantity.md
Labels: kind/cleanup, approved, lgtm, size/M

#551 update autoscaling-with-resource-metrics.md
  docs/tutorials/autoscaling-with-resource-metrics.md
  i18n/zh/docusaurus-plugin-content-docs/current/tutorials/autoscaling-with-resource-metrics.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.7/tutorials/autoscaling-with-federatedhpa.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.8/tutorials/autoscaling-with-resource-metrics.md
  versioned_docs/version-v1.7/tutorials/autoscaling-with-federatedhpa.md
  versioned_docs/version-v1.8/tutorials/autoscaling-with-resource-metrics.md
Labels: kind/documentation, approved, lgtm, size/M

#557 Add JDCloud to adopters
  src/pages/adopters.md
Labels: size/XS, approved, lgtm

#559 Add JDCloud to adopters of zh
  i18n/zh/docusaurus-plugin-content-pages/adopters.md
Labels: size/XS, approved, lgtm, tide/merge-method-squash

#555 add typo check ci action
  .github/workflows/typos.yml
  docs/contributor/contribute-docs.md
  i18n/zh/docusaurus-plugin-content-docs/current/contributor/contribute-docs.md
  typos.toml
Labels: approved, lgtm, size/M, kind/flake

#561 pin crate-ci/typos action version to v1.17.2
  .github/workflows/typos.yml
  src/pages/adopters.md
Labels: size/XS, approved, lgtm, kind/flake

#532 Add installing via operator to karmada search installation tutorials
  docs/tutorials/karmada-search.md
  i18n/zh/docusaurus-plugin-content-docs/current/tutorials/karmada-search.md
Labels: kind/documentation, approved, lgtm, size/M
