Repository karmada-io/website, pull requests merged in 2024-03, with the labels that each got.

#570 doc: add Upgrading Instruction for v1.8 to v1.9
  docs/administrator/upgrading/README.md
  docs/administrator/upgrading/v1.8-v1.9.md
  i18n/zh/docusaurus-plugin-content-docs/current/administrator/upgrading/README.md
  i18n/zh/docusaurus-plugin-content-docs/current/administrator/upgrading/v1.8-v1.9.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.9/administrator/upgrading/README.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.9/administrator/upgrading/v1.8-v1.9.md
  sidebars.js
  versioned_docs/version-v1.9/administrator/upgrading/README.md
  versioned_docs/version-v1.9/administrator/upgrading/v1.8-v1.9.md
  versioned_sidebars/version-v1.9-sidebars.json
Labels: kind/documentation, approved, lgtm, size/M

#574 fix sidebar for Karmada v1.9 API Document
  sidebars.js
  versioned_sidebars/version-v1.9-sidebars.json
Labels: kind/bug, approved, lgtm, size/S

#576 Add a note to enable the Multi-Cluster Services feature gate
  docs/tutorials/access-service-across-clusters.md
  i18n/zh/docusaurus-plugin-content-docs/current/tutorials/access-service-across-clusters.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.9/tutorials/access-service-across-clusters.md
  versioned_docs/version-v1.9/tutorials/access-service-across-clusters.md
Labels: kind/documentation, approved, lgtm, size/M

#580 Add CECloud, Neen S.p.A and Unicom Digital Tech Partners
  i18n/zh/code.json
  src/data/partnersData.tsx
  static/img/supporters/chinaunicom.png
Labels: kind/documentation, approved, lgtm, size/M

#581 add explanation about failed to propagate resource with multiple API versions
  docs/troubleshooting/trouble-shooting.md
  i18n/zh/docusaurus-plugin-content-docs/current/troubleshooting/trouble-shooting.md
Labels: kind/documentation, approved, lgtm, size/L

#577 Add more detailed instruction for global search
  docs/userguide/globalview/proxy-global-resource.md
  i18n/zh/docusaurus-plugin-content-docs/current/userguide/globalview/proxy-global-resource.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.9/userguide/globalview/proxy-global-resource.md
  versioned_docs/version-v1.9/userguide/globalview/proxy-global-resource.md
Labels: kind/documentation, approved, lgtm, size/L
