Repository karmada-io/website, pull requests merged in 2025-03, with the labels that each got.

#801 update release.md
  docs/releases.md
  i18n/zh/docusaurus-plugin-content-docs/current/releases.md
Labels: kind/documentation, approved, lgtm, size/M

#802 update v1.13 reference docs
  docs/reference/components/karmada-agent.md
  docs/reference/components/karmada-aggregated-apiserver.md
  docs/reference/components/karmada-controller-manager.md
  docs/reference/components/karmada-metrics-adapter.md
  docs/reference/components/karmada-scheduler-estimator.md
  docs/reference/components/karmada-scheduler.md
  docs/reference/components/karmada-search.md
  docs/reference/karmada-api/common-parameter/common-parameters.md
  docs/reference/karmada-api/config-resources/resource-interpreter-webhook-configuration-v1alpha1.md
  docs/reference/karmada-api/policy-resources/cluster-propagation-policy-v1alpha1.md
  docs/reference/karmada-api/policy-resources/propagation-policy-v1alpha1.md
  docs/reference/karmada-api/work-resources/resource-binding-v1alpha2.md
  docs/reference/karmadactl/karmadactl-commands/karmadactl.md
  docs/reference/karmadactl/karmadactl-commands/karmadactl_addons_enable.md
  docs/reference/karmadactl/karmadactl-commands/karmadactl_completion.md
  docs/reference/karmadactl/karmadactl-commands/karmadactl_init.md
  docs/reference/karmadactl/karmadactl-commands/karmadactl_register.md
  i18n/zh/docusaurus-plugin-content-docs/current/reference/components/karmada-agent.md
  i18n/zh/docusaurus-plugin-content-docs/current/reference/components/karmada-aggregated-apiserver.md
  i18n/zh/docusaurus-plugin-content-docs/current/reference/components/karmada-controller-manager.md
  i18n/zh/docusaurus-plugin-content-docs/current/reference/components/karmada-metrics-adapter.md
  i18n/zh/docusaurus-plugin-content-docs/current/reference/components/karmada-scheduler-estimator.md
  i18n/zh/docusaurus-plugin-content-docs/current/reference/components/karmada-scheduler.md
  i18n/zh/docusaurus-plugin-content-docs/current/reference/components/karmada-search.md
  i18n/zh/docusaurus-plugin-content-docs/current/reference/karmadactl/karmadactl-commands/karmadactl.md
  i18n/zh/docusaurus-plugin-content-docs/current/reference/karmadactl/karmadactl-commands/karmadactl_addons_enable.md
  i18n/zh/docusaurus-plugin-content-docs/current/reference/karmadactl/karmadactl-commands/karmadactl_completion.md
  i18n/zh/docusaurus-plugin-content-docs/current/reference/karmadactl/karmadactl-commands/karmadactl_init.md
  i18n/zh/docusaurus-plugin-content-docs/current/reference/karmadactl/karmadactl-commands/karmadactl_register.md
Labels: kind/documentation, approved, lgtm, size/L

#803 add upgrading v1.12 to v1.13 docs
  docs/administrator/upgrading/README.md
  docs/administrator/upgrading/v1.12-v1.13.md
  i18n/zh/docusaurus-plugin-content-docs/current/administrator/upgrading/README.md
  i18n/zh/docusaurus-plugin-content-docs/current/administrator/upgrading/v1.12-v1.13.md
  sidebars.js
Labels: kind/documentation, approved, lgtm, size/M

#771 Dockerfile: reduce karmada website container image size by 28%
  Dockerfile
  netlify.toml
  package-lock.json
Labels: kind/cleanup, approved, lgtm, size/M, tide/merge-method-squash

#806 update semi-ui
  package-lock.json
  package.json
Labels: approved, lgtm, size/L

#808 update sidebars
  versioned_sidebars/version-v1.10-sidebars.json
  versioned_sidebars/version-v1.11-sidebars.json
  versioned_sidebars/version-v1.12-sidebars.json
  versioned_sidebars/version-v1.13-sidebars.json
Labels: kind/cleanup, approved, lgtm, size/S

#807 add gen-resourcesdocs to generate API docs
  docs/reference/karmada-api/policy-resources/cluster-propagation-policy-v1alpha1.md
  docs/reference/karmada-api/policy-resources/propagation-policy-v1alpha1.md
  infra/gen-resourcesdocs/.gitignore
  infra/gen-resourcesdocs/Makefile
  infra/gen-resourcesdocs/README.md
  infra/gen-resourcesdocs/cmd/cli/cli.go
  infra/gen-resourcesdocs/cmd/cli/gvkeysmap.go
  infra/gen-resourcesdocs/cmd/cli/helpers.go
  infra/gen-resourcesdocs/cmd/cli/kwebsite.go
  infra/gen-resourcesdocs/cmd/cli/resourceslist.go
  infra/gen-resourcesdocs/cmd/cli/showtoc.go
  infra/gen-resourcesdocs/cmd/main.go
  infra/gen-resourcesdocs/config/current/fields.yaml
  infra/gen-resourcesdocs/config/current/toc.yaml
  infra/gen-resourcesdocs/go.mod
  infra/gen-resourcesdocs/go.sum
  infra/gen-resourcesdocs/hack/reference-api.sh
  infra/gen-resourcesdocs/pkg/config/categories.go
  infra/gen-resourcesdocs/pkg/config/chapter.go
  infra/gen-resourcesdocs/pkg/config/helpers.go
  infra/gen-resourcesdocs/pkg/config/output.go
  infra/gen-resourcesdocs/pkg/config/output_test.go
  infra/gen-resourcesdocs/pkg/config/toc.go
  infra/gen-resourcesdocs/pkg/config/toc_test.go
  infra/gen-resourcesdocs/pkg/kubernetes/actions.go
  infra/gen-resourcesdocs/pkg/kubernetes/apigroup.go
  infra/gen-resourcesdocs/pkg/kubernetes/apigroup_test.go
  infra/gen-resourcesdocs/pkg/kubernetes/apikind.go
  infra/gen-resourcesdocs/pkg/kubernetes/apiversion.go
  infra/gen-resourcesdocs/pkg/kubernetes/apiversion_test.go
  infra/gen-resourcesdocs/pkg/kubernetes/extensions.go
  infra/gen-resourcesdocs/pkg/kubernetes/extensions_test.go
  infra/gen-resourcesdocs/pkg/kubernetes/key.go
  infra/gen-resourcesdocs/pkg/kubernetes/linkend.go
  infra/gen-resourcesdocs/pkg/kubernetes/parameters.go
  infra/gen-resourcesdocs/pkg/kubernetes/property.go
  infra/gen-resourcesdocs/pkg/kubernetes/property_test.go
  infra/gen-resourcesdocs/pkg/kubernetes/resource.go
  infra/gen-resourcesdocs/pkg/kubernetes/resource_test.go
  infra/gen-resourcesdocs/pkg/kubernetes/spec.go
  infra/gen-resourcesdocs/pkg/kubernetes/spec_test.go
  infra/gen-resourcesdocs/pkg/openapi/openapi.go
  infra/gen-resourcesdocs/pkg/openapi/openapi_test.go
  infra/gen-resourcesdocs/pkg/outputs/interface.go
  infra/gen-resourcesdocs/pkg/outputs/kwebsite/chapter.go
  infra/gen-resourcesdocs/pkg/outputs/kwebsite/files.go
  infra/gen-resourcesdocs/pkg/outputs/kwebsite/kwebsite.go
  infra/gen-resourcesdocs/pkg/outputs/kwebsite/links.go
  infra/gen-resourcesdocs/pkg/outputs/kwebsite/part.go
  infra/gen-resourcesdocs/pkg/outputs/kwebsite/section.go
  infra/gen-resourcesdocs/templates/chapter-single-definition.tmpl
  infra/gen-resourcesdocs/templates/chapter.tmpl
  infra/gen-resourcesdocs/templates/part-index.tmpl
  versioned_docs/version-v1.13/reference/karmada-api/policy-resources/cluster-propagation-policy-v1alpha1.md
  versioned_docs/version-v1.13/reference/karmada-api/policy-resources/propagation-policy-v1alpha1.md
Labels: kind/feature, size/XXL, approved, lgtm

#809 update semi-ui
  package-lock.json
  package.json
Labels: approved, lgtm, size/L

#812 improve document-releasing process
  docs/developers/document-releasing.md
  i18n/zh/docusaurus-plugin-content-docs/current/developers/document-releasing.md
Labels: kind/documentation, approved, lgtm, size/M

#815 Add rednote to adopters
  i18n/zh/docusaurus-plugin-content-pages/adopters.md
  src/pages/adopters.md
Labels: size/XS, kind/documentation, approved, lgtm

#814 update install-binary.md to adjust the installation order
  docs/installation/install-binary.md
  i18n/zh/docusaurus-plugin-content-docs/current/installation/install-binary.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.11/installation/install-binary.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.12/installation/install-binary.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.13/installation/install-binary.md
  versioned_docs/version-v1.11/installation/install-binary.md
  versioned_docs/version-v1.12/installation/install-binary.md
  versioned_docs/version-v1.13/installation/install-binary.md
Labels: kind/documentation, approved, lgtm, size/L

#813 Add binding address configuration for security considerations
  docs/administrator/security/security-considerations.md
  i18n/zh/docusaurus-plugin-content-docs/current/administrator/security/security-considerations.md
Labels: kind/documentation, approved, lgtm, size/L
