Repository karmada-io/website, pull requests merged in 2025-09, with the labels that each got.

#883 Add explanations for cluster failover configuration in the failover overview
  docs/key-features/features.md
  docs/userguide/failover/cluster-failover.md
  docs/userguide/failover/failover-overview.md
  i18n/zh/docusaurus-plugin-content-docs/current/key-features/features.md
  i18n/zh/docusaurus-plugin-content-docs/current/userguide/failover/cluster-failover.md
  i18n/zh/docusaurus-plugin-content-docs/current/userguide/failover/failover-overview.md
  sidebars.js
Labels: kind/documentation, approved, lgtm, size/L

#853 add upgrade guide
  docs/administrator/upgrading/README.md
  docs/administrator/upgrading/how-to-upgrade.md
  sidebars.js
Labels: kind/documentation, approved, lgtm, size/L

#891 publish official blog post of Bloomberg
  blog/2025-09-11-bloomberg-officially-joined-the-karmada-adopter-group/bloomberg.md
  i18n/zh/docusaurus-plugin-content-blog/2025-09-11-bloomberg-officially-joined-the-karmada-adopter-group/bloomberg.md
  static/img/supporters/bloomberg.png
Labels: kind/documentation, approved, lgtm, size/M

#894 [en] Add case study: daocloud.md
  docs/casestudies/daocloud.md
  docs/resources/casestudies/daocloud/auto_convert.PNG
  docs/resources/casestudies/daocloud/kairship_architecture.PNG
  docs/resources/casestudies/daocloud/karmada_operator.PNG
  docs/resources/casestudies/daocloud/multi_karmada.PNG
  docs/resources/casestudies/daocloud/multi_tenant.PNG
  docs/resources/casestudies/daocloud/prompt.PNG
  docs/resources/casestudies/daocloud/ui.PNG
  i18n/zh/docusaurus-plugin-content-docs/current/casestudies/daocloud.md
Labels: kind/documentation, approved, lgtm, size/L

#900 docs: translate “Deploy ANP For Pull mode” to Chinese
  i18n/zh/docusaurus-plugin-content-docs/current/userguide/clustermanager/working-with-anp.md
Labels: approved, lgtm, size/M

#901 update API reference
  docs/reference/karmada-api/app-resources/workload-rebalancer-v1alpha1.md
  docs/reference/karmada-api/auto-scaling-resources/cron-federated-hpa-v1alpha1.md
  docs/reference/karmada-api/auto-scaling-resources/federated-hpa-v1alpha1.md
  docs/reference/karmada-api/cluster-resources/cluster-v1alpha1.md
  docs/reference/karmada-api/config-resources/resource-interpreter-customization-v1alpha1.md
  docs/reference/karmada-api/config-resources/resource-interpreter-webhook-configuration-v1alpha1.md
  docs/reference/karmada-api/networking-resources/multi-cluster-ingress-v1alpha1.md
  docs/reference/karmada-api/networking-resources/multi-cluster-service-v1alpha1.md
  docs/reference/karmada-api/policy-resources/cluster-override-policy-v1alpha1.md
  docs/reference/karmada-api/policy-resources/cluster-propagation-policy-v1alpha1.md
  docs/reference/karmada-api/policy-resources/cluster-taint-policy-v1alpha1.md
  docs/reference/karmada-api/policy-resources/federated-resource-quota-v1alpha1.md
  docs/reference/karmada-api/policy-resources/override-policy-v1alpha1.md
  docs/reference/karmada-api/policy-resources/propagation-policy-v1alpha1.md
  docs/reference/karmada-api/remedy-resources/remedy-v1alpha1.md
  docs/reference/karmada-api/search-resources/resource-registry-v1alpha1.md
  docs/reference/karmada-api/work-resources/cluster-resource-binding-v1alpha2.md
  docs/reference/karmada-api/work-resources/resource-binding-v1alpha2.md
  docs/reference/karmada-api/work-resources/work-v1alpha1.md
  infra/gen-resourcesdocs/Makefile
Labels: kind/cleanup, approved, lgtm, size/L
