Repository karmada-io/website, pull requests merged in 2025-08, with the labels that each got.

#870 clarify supported file formats in karmadactl interpret doc
  docs/reference/karmadactl/karmadactl-commands/karmadactl_create.md
  docs/reference/karmadactl/karmadactl-commands/karmadactl_interpret.md
Labels: size/XS, kind/documentation, approved, lgtm, tide/merge-method-squash

#875 Add new supporters
  src/data/supporters.js
Labels: size/XS, approved, lgtm

#871 Add Bloomberg as adopter
  src/pages/adopters.md
Labels: kind/documentation, approved, lgtm, size/M

#880 Get adopter onboard: `Alibaba Cloud`
  i18n/zh/docusaurus-plugin-content-pages/adopters.md
  src/data/supporters.js
  src/pages/adopters.md
  static/img/supporters/alibabacloud.png
Labels: size/XS, kind/documentation, approved, lgtm
