Repository karmada-io/website, pull requests merged in 2025-05, with the labels that each got.

#831 add chinese doc for karmadactl init config documents
  i18n/zh/docusaurus-plugin-content-docs/current/reference/karmadactl/karmadactl-config.v1alpha1.md
Labels: kind/documentation, approved, lgtm, size/L

#833 bump semi-ui
  package-lock.json
  package.json
Labels: approved, lgtm, size/L

#835 Adding documentation for resource quota enforcement feature
  docs/resources/key-features/federated-quota-enforcement.png
  docs/userguide/bestpractices/federated-resource-quota.md
Labels: kind/documentation, approved, lgtm, size/M

#834 Add Kubernetes compatibility docs
  docs/administrator/compatibility/compatibility.md
  i18n/zh/docusaurus-plugin-content-docs/current.json
  i18n/zh/docusaurus-plugin-content-docs/current/administrator/compatibility/compatibility.md
  sidebars.js
Labels: kind/documentation, approved, lgtm, size/L

#841 translate profiling-karmada.md to Chinese
  i18n/zh/docusaurus-plugin-content-docs/current/developers/profiling-karmada.md
Labels: approved, lgtm, size/M
