Repository karmada-io/website, pull requests merged in 2025-06, with the labels that each got.

#840 translate federated-reousrce-quota.md to Chinese
  i18n/zh/docusaurus-plugin-content-docs/current/resources/key-features/federated-quota-enforcement.png
  i18n/zh/docusaurus-plugin-content-docs/current/userguide/bestpractices/federated-resource-quota.md
Labels: kind/documentation, approved, lgtm, size/L

#842 translate contributor docs to Chinese
  i18n/zh/docusaurus-plugin-content-docs/current/contributor/cherry-picks.md
  i18n/zh/docusaurus-plugin-content-docs/current/contributor/github-workflow.md
  i18n/zh/docusaurus-plugin-content-docs/current/resources/contributor/git_workflow.png
Labels: kind/documentation, approved, lgtm, size/L

#845 Add upgrading v1.13 to v1.14 docs
  docs/administrator/upgrading/README.md
  docs/administrator/upgrading/v1.13-v1.14.md
  i18n/zh/docusaurus-plugin-content-docs/current/administrator/upgrading/README.md
  i18n/zh/docusaurus-plugin-content-docs/current/administrator/upgrading/v1.13-v1.14.md
  sidebars.js
Labels: kind/documentation, approved, lgtm, size/M

#846 update toc file according to the latest Karmada API resources
  infra/gen-resourcesdocs/config/current/toc.yaml
Labels: size/XS, kind/documentation, approved, lgtm

#843 document cluster taint management
  docs/resources/userguide/failover/clustertaintpolicy.drawio
  docs/resources/userguide/failover/clustertaintpolicy.png
  docs/userguide/failover/cluster-taint-management.md
  sidebars.js
Labels: kind/feature, kind/documentation, approved, lgtm, size/L

#851 Nominate windsonsea as the approver
  OWNERS
Labels: size/XS, kind/cleanup, approved, lgtm
