Repository karmada-io/website, pull requests merged in 2025-04, with the labels that each got.

#819 update semi-ui to 2.77.1
  package-lock.json
  package.json
Labels: approved, lgtm, size/L

#818 add more description for op/cop resourceSelectors
  docs/userguide/scheduling/override-policy.md
  i18n/zh/docusaurus-plugin-content-docs/current/userguide/scheduling/override-policy.md
Labels: kind/documentation, approved, lgtm, size/M

#826 Fix syntax for referencing POD_IP
  docs/administrator/security/security-considerations.md
  i18n/zh/docusaurus-plugin-content-docs/current/administrator/security/security-considerations.md
Labels: size/XS, kind/cleanup, approved, lgtm

#830 Update namespace-management document
  i18n/zh/docusaurus-plugin-content-docs/current/userguide/bestpractices/namespace-management.md
Labels: kind/documentation, approved, lgtm, size/M
