Repository karmada-io/website, pull requests merged in 2025-02, with the labels that each got.

#789 add adopter for transwarp
  i18n/zh/docusaurus-plugin-content-pages/adopters.md
  src/pages/adopters.md
Labels: size/XS, kind/documentation, approved, lgtm

#791 update asciinema-player
  package-lock.json
  package.json
Labels: approved, lgtm, size/S

#794 update semi-ui
  package-lock.json
  package.json
Labels: approved, lgtm, size/L

#795 fix: karmada operator field typo
  docs/tutorials/karmada-search.md
  i18n/zh/docusaurus-plugin-content-docs/current/tutorials/karmada-search.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.10/tutorials/karmada-search.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.11/tutorials/karmada-search.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.12/tutorials/karmada-search.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.9/tutorials/karmada-search.md
  versioned_docs/version-v1.10/tutorials/karmada-search.md
  versioned_docs/version-v1.11/tutorials/karmada-search.md
  versioned_docs/version-v1.12/tutorials/karmada-search.md
  versioned_docs/version-v1.9/tutorials/karmada-search.md
Labels: kind/documentation, approved, lgtm, size/S

#796 add priorityclass configuration feature dos
  docs/administrator/configuration/priority-class-configuration.md
  i18n/zh/docusaurus-plugin-content-docs/current/administrator/configuration/priority-class-configuration.md
  sidebars.js
Labels: kind/documentation, approved, lgtm, size/L

#800 update semi-ui
  package-lock.json
  package.json
Labels: approved, lgtm, size/L

#798 Add new adopter iFLYTEK
  i18n/zh/docusaurus-plugin-content-pages/adopters.md
  src/pages/adopters.md
Labels: size/XS, kind/documentation, approved, lgtm
