Repository karmada-io/website, pull requests merged in 2025-01, with the labels that each got.

#779 update cluster-registration.md to introduce how to unregister a cluster using the unregister command
  docs/userguide/clustermanager/cluster-registration.md
  i18n/zh/docusaurus-plugin-content-docs/current/userguide/clustermanager/cluster-registration.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.12/userguide/clustermanager/cluster-registration.md
  versioned_docs/version-v1.12/userguide/clustermanager/cluster-registration.md
Labels: kind/documentation, approved, lgtm, size/L

#778 update semi-ui
  package-lock.json
  package.json
Labels: approved, lgtm, size/L

#781 update dependencies
  package-lock.json
  package.json
Labels: approved, lgtm, size/L

#784 update semi-ui
  package-lock.json
  package.json
Labels: approved, lgtm, size/L

#786 Update cluster-resources.md
  docs/userguide/scheduling/cluster-resources.md
Labels: size/XS, approved, lgtm

#785 add karmada security audit blog
  blog/2025-01-17-karmada-security-audit/karmada-security-audit.md
Labels: kind/documentation, approved, lgtm, size/M

#787 publish karmada security audit result in Chinese
  i18n/zh/docusaurus-plugin-content-blog/2025-01-17-karmada-security-audit/karmada-security-audit.md
Labels: kind/documentation, approved, lgtm, size/M

#788 Updated Karmada installation documentation for non-root users
  docs/installation/installation.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.3/installation/installation.md
  versioned_docs/version-v1.10/installation/installation.md
  versioned_docs/version-v1.11/installation/installation.md
  versioned_docs/version-v1.12/installation/installation.md
  versioned_docs/version-v1.3/installation/installation.md
  versioned_docs/version-v1.4/installation/installation.md
  versioned_docs/version-v1.5/installation/installation.md
  versioned_docs/version-v1.6/installation/installation.md
  versioned_docs/version-v1.7/installation/installation.md
  versioned_docs/version-v1.8/installation/installation.md
  versioned_docs/version-v1.9/installation/installation.md
Labels: approved, lgtm, size/M
