Repository karmada-io/website, pull requests merged in 2025-07, with the labels that each got.

#858 add karmada-v1.14 blog
  blog/2025-05-30-karmada-v1.14/img/clustertaintpolicy.png
  blog/2025-05-30-karmada-v1.14/img/contributors.png
  blog/2025-05-30-karmada-v1.14/karmada-v1.14.md
  i18n/zh/docusaurus-plugin-content-blog/2025-05-30-karmada-v1.14/img/clustertaintpolicy.png
  i18n/zh/docusaurus-plugin-content-blog/2025-05-30-karmada-v1.14/img/contributors.png
  i18n/zh/docusaurus-plugin-content-blog/2025-05-30-karmada-v1.14/karmada-v1.14.md
Labels: kind/documentation, approved, lgtm, size/L

#861 update semi-ui to 2.82.1 & asciinema-player to 3.10.0
  package-lock.json
  package.json
Labels: approved, lgtm, size/L

#862 update semi-ui to 2.83.0
  package-lock.json
  package.json
Labels: approved, lgtm, size/L

#864 Add leinao to adopters
  i18n/zh/docusaurus-plugin-content-pages/adopters.md
  src/pages/adopters.md
  static/img/supporters/leinao.png
Labels: size/XS, approved, lgtm

#866 bump semi-ui to 2.84.0
  package-lock.json
  package.json
Labels: approved, lgtm, size/L
